### ISSUE TITLE
Use enum for appCommandOutputFormat

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/appengine-plugins-core#107]
GCloud.outputFormat

See https://cloud.google.com/sdk/docs/scripting-gcloud

> You can minimize the impact of those changes by using the --format flag to format the output with one of the following: --format=json|yaml|csv|text|list to specify values to be returned. Run $ gcloud topic formats for more options.

**Comment by patflynn** [comment]
@loosebazooka @meltsufin 
I know we talked about making the APIs return result types so that the clients didn't have to parse the output.  Is that still the plan?

**Comment by loosebazooka** [comment]
Yeah, so we want to do a refactor of this, but we're working on the plugin milestones for now. I suspect time becomes available near the June/July border

**Comment by elharo** [comment]
This seems to eliminate the possibility of using projections: https://cloud.google.com/sdk/gcloud/reference/topic/projections

which would actually be useful. We might want to explore the possibility of per-command formats, but that's a separate issue, so I'm going to close this one.
