### ISSUE TITLE
add pre-push check

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/appengine-plugins-core#114]
Whatever travis is running to validate a PR should be run prior to pushing to the git remote.

**Comment by loosebazooka** [comment]
@patflynn what do you mean?

**Comment by patflynn** [comment]
a presubmit check using a git hook to validate as much as we can do quickly.

**Comment by meltsufin** [comment]
Currently, `mvn clean install` is what Travis uses to validate the build. We should all have a habit of building before pushing a change, but I'm weary of putting in a git hook for this. A build can take a minute or two, and when I do `git push`, I don't really want to wait at that point.

**Comment by patflynn** [comment]
I agree. It should be anything we can do that's fast. So possibly only
build and lint. Or build and lint and fast tests.
=
