### ISSUE TITLE
Javadoc for RunConfiguration

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#117]
app-tools-lib-for-java/src/main/java/com/google/cloud/tools/appengine/api/devserver/RunConfiguration.java needs complete JavaDoc on each field explaining what it is, what it's used for, legal values, etc.

**Comment by meltsufin** [comment]
Agreed. This also applies to all other *Configuration interfaces.

**Comment by JoeWang1127** [comment]
close as not planned
