### ISSUE TITLE
Rename RunConfiguration#getAppYamls to reflect that other files/dir can be passed as runnable

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/appengine-plugins-core#132]

**Comment by loosebazooka** [comment]
@meltsufin we talked about this before? What do you think about changing this to deployables?

**Comment by meltsufin** [comment]
Renaming to 'deployables' sounds good to me. It would make it more consistent with staging/deploy config naming.

**Comment by elharo** [comment]
appears to be obsolete
