### ISSUE TITLE
Consistency in CloudSdk Listener methods

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#133]
Here's some code we wrote in eclipse:
-    CloudSdk cloudSdk = new CloudSdk.Builder()
-        .addStdOutLineListener(outputListener)
-        .addStdErrLineListener(outputListener)
-        .startListener(localAppEngineStartListener)
-        .exitListener(localAppEngineExitListener)
-        .build();

why addStdOutLineListener and addStdErrLineListener but not addStartListener and addExitListener?

We should be consistent here.

**Comment by meltsufin** [comment]
This is related to #85. The idea there is to use varargs and remove the `add` prefix. This would make all of the methods consistent.

**Comment by elharo** [comment]
Is there a reason there's only one exit and start listener?

Is there/should there be a way to remove a listener?

**Comment by loosebazooka** [comment]
obsolete
