### ISSUE TITLE
FR: Jetty Quickstart should be supported

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/appengine-plugins-core#155]
Jetty [Quickstart](http://www.eclipse.org/jetty/documentation/9.4.x/quickstart-webapp.html) was developed for GAE and is a part of both existing maven plugins.  We should support it somehow in all the new ones. [blog](https://webtide.com/jetty-9-quick-start/)

**Comment by elharo** [comment]
sounds good. Please file an issue for that.

On Thu, Jul 7, 2016 at 4:18 PM, Les Vogel <notifications@github.com> wrote:

> Jetty Quickstart
> <http://www.eclipse.org/jetty/documentation/9.4.x/quickstart-webapp.html>
> was developed for GAE and is a part of both existing maven plugins. We
> should support it somehow in all the new ones. blog
> <https://webtide.com/jetty-9-quick-start/>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/GoogleCloudPlatform/app-tools-lib-for-java/issues/155>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA9X6NsSnzVR_R77f4qsxWReP1VdxiZoks5qTV78gaJpZM4JHdXn>
> .
>



-- 
Elliotte Rusty Harold
elharo@macfaq.com
