### ISSUE TITLE
ProcessExitListener should return the process instance too

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/appengine-plugins-core#178]
If the `CloudSdk` instance is used to run async processes and more than one is being executed at the same time (e.g 2 long running deploy for 2 application), the `ProcessExitListener` will get only the exit code, but not the source, so it cannot tell which process has exited.

If the intended usage is to use one `CloudSdk` instance per command, then that should be documented.

**Comment by meltsufin** [comment]
The same would apply to the other listeners, like the `ProcessOutputLineListener`. You wouldn't know which process the output is coming form.

I think it's best to just document that `CloudSdk` only support one concurrent execution, or should only be used once per command.

**Comment by loosebazooka** [comment]
obsolete
