### ISSUE TITLE
GAE Standard staging app.yaml fix might break in async execution

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/appengine-plugins-core#179]
If the execution is set to async, then code starting at this line: https://github.com/GoogleCloudPlatform/app-tools-lib-for-java/blob/master/src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineStandardStaging.java#L86 can execute before the staging operation finishes/creates the app.yaml.

**Comment by JoeWang1127** [comment]
close as not planned
