### ISSUE TITLE
Operations should return java.util.concurrent.Future

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/appengine-plugins-core#180]
Operations (e.g. standard staging, deploy) should return a Future object to allow easier cancellation of the operation on the caller's end.

**Comment by meltsufin** [comment]
I would also add that the Future should return a meaningful result of the operation.

**Comment by loosebazooka** [comment]
check out this branch, maybe we can work from here https://github.com/GoogleCloudPlatform/app-tools-lib-for-java/tree/futures

**Comment by loosebazooka** [comment]
See com.google.cloud.tools.appengine.v2.deploy.DeployExample

**Comment by CMahesh** [comment]
is the this issue completed ?

**Comment by loosebazooka** [comment]
obsolete
