### ISSUE TITLE
PathResolvers configuration for tests

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/appengine-plugins-core#183]
@briandealwis it seems like the whole point of the path resolver was to allow tests to control where the SDK will be found. Why not just explicitly define the path to SDK when building it?

https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java#L450

I'm just trying to understand this section of code.

**Comment by briandealwis** [comment]
It's necessary for testing the Eclipse preferences-based resolver.

https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/blob/c610d5b9a30b7678dc7eb1db0b8998b8fba0543b/plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkPreferenceResolverTest.java#L52

**Comment by briandealwis** [comment]
Hmm, I thought I added a test to verify the ordering of resolvers.
