### ISSUE TITLE
Create flag to disable error and output redirection

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/appengine-plugins-core#185]
The IntelliJ run/debug configuration framework prints log and output for a process by calling `process.getErrorStream()` and `process.getOutputStream()` and printing that to its console. However, when we do `processBuilder.redirectError()` or `processBuilder.redirectOutput()`, `getErrorStream()` and `getOutputStream()` return NullInputSource, which causes nothing to be printed in the console.

The console also doesn't seem to be available anywhere when we have control, so we can't add log listeners to the process.

We should create a flag to disable error and output inheritance.

**Comment by loosebazooka** [comment]
How does intellij have access to the process object?

**Comment by elharo** [comment]
seems to have been fixed a long time ago
