### ISSUE TITLE
Provide AppEngine SDK jars

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/appengine-plugins-core#186]
The Cloud SDK includes a set of jar files for AppEngine apps that are necessary for configure project classpaths in IDEs. Rather than explicitly configure them in code, the library should return a list of jars with metadata required by the IDEs.  For now, it could answer a set of ClasspathDetails objects that includes URIs for the binary jar, javadocs, and source, and whether it is considered intrinsic (and shouldn't be included in the deploy).

**Comment by patflynn** [comment]
+1

**Comment by elharo** [comment]
do we want this returning maven central info?

**Comment by patflynn** [comment]
I am not sure I would push this into the library.  But open to discussion.

**Comment by briandealwis** [comment]
Closing as this was deemed to be outside of the scope of this library.
