### ISSUE TITLE
Add JVM args fix for Java 8 timezone error on local run

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/appengine-plugins-core#188]
When doing a local run of an AE standard app with JDK 8 we get the following runtime error:

![image](https://cloud.githubusercontent.com/assets/1735744/17783770/7d677692-6547-11e6-994a-a03fe6f01788.png)

The maven plugin already has a [fix for this](https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/master/src/main/java/com/google/cloud/tools/maven/RunMojo.java#L213), but this logic is used by several clients and should therefore be moved to this library.

**Comment by briandealwis** [comment]
Or fixed in dev_appserver; I couldn't find it on the public repositories.

**Comment by etanshaul** [comment]
Yea, that would be ideal.

**Comment by patflynn** [comment]
@etanshaul can we close this issue?

**Comment by etanshaul** [comment]
I believe it was fixed with dev app server 1.9.42 per this thread: https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/811#issuecomment-241025322

But I'll check to make sure

**Comment by etanshaul** [comment]
@joaoandremartins since you referenced that issue in the PR linked to above, do you happen to know the status of this?

**Comment by chanseokoh** [comment]
FYI, CT4E removed this fix: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/964 (Not that I personally checked if this is working.)

**Comment by joaoandremartins** [comment]
This issue was fixed in the GAE SDK 1.9.42 release. Any flags we added (I don't think we added any) should be removed. I think the Eclipse folks added a few.

**Comment by etanshaul** [comment]
Ok thanks. I also checked the common lib and IJ and no flags are there presently.. Closing this issue then.
