### ISSUE TITLE
platform/bundledpython/python.exe may not exist in Cloud SDK on Windows

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/appengine-plugins-core#189]
It then fails to run a local server.

**Comment by meltsufin** [comment]
The Python executable lookup should be done in this order:

1. Use the path found in the CLOUDSDK_PYTHON environment variable if set.
2. Use the bundled Python if installed.
3. Rely on Python being in PATH by invoking "python" directly.

**Comment by briandealwis** [comment]
`GOOGLE_CLOUD_PYTHON`, to be consistent with `GOOGLE_CLOUD_SDK_HOME`?

**Comment by chanseokoh** [comment]
`CLOUDSDK_PYTHON` is what gcloud is already using (http://stackoverflow.com/questions/30832990/google-cloud-sdk-set-environment-variable-python-linux), and seems like we'll just look for it too.

**Comment by elharo** [comment]
see

  private Path getWindowsPythonPath() {
    return getSdkPath().resolve(WINDOWS_BUNDLED_PYTHON);
  }

in CloudSdk
