### ISSUE TITLE
Provide a way to validate a Cloud SDK without having to instantiate a CloudSdk object

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/appengine-plugins-core#213]
At the moment, we validate a Cloud SDK by checking if its file system path meets a number of constraints (e.g., exists, is a directory, contains certain files, etc.)

We're moving to a validate-per-action strategy, but we'll still need to be able to validate a Cloud SDK earlier, when the user specifies one.

**Comment by elharo** [comment]
I don't follow why this is needed. Is there some part of constructing a CloudSdk object that's particularly expensive?

**Comment by joaoandremartins** [comment]
I agree it is not an expensive operation. But that might change in the future and, conceptually, it doesn't make sense to me. That appeared to be the general sentiment when I discussed this two weeks ago.

I'm just not sure about whether the end result will be worth the effort. It could be something to consider when there are no other pressing issues needing to be addressed.
