### ISSUE TITLE
App Engine Admin API

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#214]
Explore using this for deploys and taking the Cloud SDK out of the picture:

https://cloudplatform.googleblog.com/2016/08/automate-deployments-and-traffic-splitting-with-the-App-Engine-Admin-API.html

**Comment by meltsufin** [comment]
This is the corresponding [Java App Engine Admin API client library](https://developers.google.com/api-client-library/java/apis/appengine/v1beta4).

**Comment by elharo** [comment]
That's the beta of the Java client library. We need the release version.

**Comment by meltsufin** [comment]
I don't think there is one yet.

**Comment by elharo** [comment]
https://developers.google.com/api-client-library/java/apis/appengine/v1
