### ISSUE TITLE
Passing java debug arguments to dev_appserver

### ISSUE THREAD

**Issue by aleemstreak** [GoogleCloudPlatform/appengine-plugins-core#216]
running `dev_appserver.py --jvm_flag='-Xdebug' --jvm_flag='-D-agentlib:jdwp=transport=dt_socket,address=7000,server=y,suspend=false' somewebapp` doesn't seem to correctly pass the debug arguments to the dev server. It doesn't seem like you can connect a debugger to that port...

**Comment by elharo** [comment]
I suspect this isn't the right project to report this in. It sounds like your problem is with the Cloud SDK more directly. Are you actually using the appengine-plugins-core library?

**Comment by aleemstreak** [comment]
Not using that lib directly but I saw this issue but saw this issue and thought it was similar so filed here:

https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/121

**Comment by briandealwis** [comment]
@aleemstreak you have 2 syntax errors:
  - The `-D` means the JVM is interpreting the rest as a system property
  - the boolean arguments for `jdwp` are `y` or `n`, not `true` or `false`:

```
$ dev_appserver.py —jvm_flag='-Xdebug' --jvm_flag='-agentlib:jdwp=transport=dt_socket,address=7000,server=y,suspend=n' target/example-appengine-archetype-0.0.1-SNAPSHOT
INFO     2016-09-19 01:14:07,548 devappserver2.py:769] Skipping SDK update check.
WARNING  2016-09-19 01:14:07,660 simple_search_stub.py:1146] Could not read search indexes from /var/folders/v7/13_yd9zd4ls5xj_7dqgkkz840000gn/T/appengine.your-app-id.bsd/search_indexes
INFO     2016-09-19 01:14:07,665 api_server.py:205] Starting API server at: http://localhost:59299
INFO     2016-09-19 01:14:07,674 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
INFO     2016-09-19 01:14:07,676 admin_server.py:116] Starting admin server at: http://localhost:8000
Listening for transport dt_socket at address: 7000
```
