### ISSUE TITLE
Handle dev_appserver.py auto-install prompt for app-engine-java component

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/appengine-plugins-core#217]
The next release of the Cloud SDK will contain a fix that makes dev_appserver.py prompt the user to install app-engine-java component. The library currently doesn't handle interactive prompts for dev_appserver.py.

Internal ref b/31436469

**Comment by elharo** [comment]
We may want to ignore this and go our own way here. E.g. continue to detect that appengine-java-components is not installed and manage that situation ourselves. I'm skeptical that we want to attempt to interact with gcloud like a user.

**Comment by patflynn** [comment]
let's just push on gcloud to have a non-interactive flow for starting the
dev appserver and autoinstalling the java component.

**Comment by meltsufin** [comment]
I asked a question about it in the above-referenced internal bug report, but no answer yet.

**Comment by meltsufin** [comment]
Use the `CLOUDSDK_CORE_DISABLE_PROMPTS=1` environment variable for the quiet mode.
