### ISSUE TITLE
CloudSdk.getVersion, CloudSdk.getComponents

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#241]
CT4J would like to check the installed version of the Cloud SDK (131, 132, etc.) as well as the version s of various components. I'm not immediately sure what this feature should look like but it's probably part of the CloudSdk class.

**Comment by aslo** [comment]
Self-assigning in order to unblock https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1051
