### ISSUE TITLE
Provide support for installing and updating components

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/appengine-plugins-core#244]
Both [IntelliJ](https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1051) and [Eclipse](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/367) have hit problems due to missing or out-of-date `gcloud` or `app-engine-java` components.  Currently in the Eclipse plugin we prompt the user to update with a command-line.  But both @chanseokoh and I have hit situations where the `gcloud` picked up by Eclipse was not the same as that picked up on our command-line. It would be useful for the library to support installing and updating components, which would support a single-click UI experience to update the necessary components (or automatically as required).

**Comment by patflynn** [comment]
I can see the case for knowing the version of the cloud SDK and updating
it.  However now that we have no explicit need to install the Java
components I don't see any use-cases for needing to install or know about
what components are installed.

**Comment by briandealwis** [comment]
This is now supported by the Managed SDK option.
