### ISSUE TITLE
Bundle Cloud SDK

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#246]
This is a big one. UX research, as well as our own testing, consistently shows that relying on a user-installed Cloud SDK is a major source of confusion for end users, for multiple reasons.

I'd like to revisit the possibility of bundling the Cloud SDK with this library so that users do not need to separately download, install, and configure it. 

This would make a lot of other issues moot.

**Comment by patflynn** [comment]
we should prioritize this in Q1.

**Comment by chanseokoh** [comment]
We may need to embed emulators too: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/667

Each of the emulators needs its own components installed.

**Comment by briandealwis** [comment]
Shall we close this?
