### ISSUE TITLE
Running multiple java modules causes memory bloat

### ISSUE THREAD

**Issue by aleemstreak** [GoogleCloudPlatform/appengine-plugins-core#247]
Using this project I run a multi-module appengine app. It has 8 java modules (some flex, some standard).

Each module run using this library causes one java process to be created for each module. Each java process somehow takes 1GB of ram so running the devserver eats 8GB total for me.

1) Is 1GB normal to run a single module?
2) Is there a way to get all the modules to run under the same java process?
3) Is this a dev_appserver.py issue? Where can I file a bug with them?

**Comment by meltsufin** [comment]
You're thinking correctly that this is more of a `dev_appserver.py` issue. You should file this in the [App Engine Project Issue Tracker](https://code.google.com/p/googleappengine/issues/list).
@patflynn @ludoch FYI

**Comment by aleemstreak** [comment]
Awesome thanks!

Filed here: https://code.google.com/p/googleappengine/issues/detail?id=13380
ᐧ

**Comment by aleemstreak** [comment]
( https://www.streak.com )
( https://www.streak.com/careers )

We're very proud to close 2016 with major feature
releases including Box redesign and a brand new Contacts and
Organizations feature. It's never been faster or easier to use
Streak. Adding content to a box? Just start typing! Tracking
multiple people involved in one box? Add a Contact (or more) with
one click. Looking for an at-a-glance understanding? Fresh box
design surfaces everything relevant.

Finally, share the Streak love by helping celebrate our updates
on Product Hunt ( https://www.producthunt.com/posts/streak-2-0-contacts ) right
now! An upvote would be hugely appreciated!

New! Streak Contacts

Tracking multiple people involved in one box is now
significantly improved. Here are four big reasons to be excited
for Contacts and Organizations: * More data, less data entry:
We'll automatically enrich Streak Contacts using multiple sources
including your existing Google Contacts Data.
* Act on your Contact information from the Box, Pipeline, or
Contact: Send an email, click-to-call, send Calendar invite, or
start a Hangout/Videochat with any Contact
* Simple visibilty: See all boxes containing a Contact
* Collaborate: Easily share details with your entire Streak Team

Contacts Details

... and Organizations!

Adding Organizations to Boxes in Streak offers the
same benefits as Contacts, including:
* Share Organization information with your whole
Streak Team
* Add the same Organization multiple boxes
* View all boxes associated with the Organization

Organization Details

Easy Access to Contacts

All Streak Contacts are now available via the main
Gmail search bar. Begin typing the name of a Contact and we'll
offer autocomplete results that can take you directly to that
Contact (or Organization).

Learn More

Simplified 'Add to Box'

You offered a ton of feedback and we listened! You'll
now find the top of every box includes an easy field waiting for
you to input content. Just start typing! After you've added
content, choose to save as a Comment, Task, Call Log, or Meeting
Note.

Learn More

More questions? Email support@streak.com (
mailto:support@streak.com )

Additional Resources: Knowledge Base ( http://support.streak.com ), Streak Blog ( http://blog.streak.com )

Feel free to Unsubscribe ( http://track.customer.io/unsubscribe/MzEwNTU6FvGiAmQAAnMAFxpSeBoBWC6o5RMVFhhYWHVlAW06NDMxNzg1AA== )

( https://twitter.com/streak )
( https://facebook.com/streakgmail )
( http://blog.streak.com )
