### ISSUE TITLE
Update Javadoc about CloudSdkNotFoundException and CloudSdkOutOfDateException

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/appengine-plugins-core#279]
There are several public-facing methods that (directly or indirectly) call `validateCloudSdk()`:

`runAppCommand()`
`runSourceCommand()`
`getComponents()`
`runDevAppServerCommand(List)`
`runDevAppServerCommand(List, Map<>)`

The last two methods document that they throw `CloudSdkNotFoundException`:

`@throws CloudSdkNotFoundException when the Cloud SDK is not installed where expected`

However, the others don't document it. Moreover, after #276, all of them will additionally throw `CloudSdkOutOfDateException`, so this should be documented too.

**Comment by elharo** [comment]
This would not have been an issue if these were checked exceptions...

**Comment by chanseokoh** [comment]
I have identified a few more public methods, although these methods neither have a Javadoc at all nor document any `@throws`:

- `CloudSdkAppEngineDevServer.run()`: calls `runDevAppServerCommand()`.
- `CloudSdkGenRepoInfoFile.generate()`: calls `runSourceCommand()`.
- `CloudSdkAppEngineDeployment.deploy()`: calls `runAppCommand()`.
- `CloudSdkAppEngineGenConfig.genConfig()`: calls `runAppCommand()`.
- `CloudSdkAppEngineInstances.enableDebug()`: indirectly calls `runAppCommand()`.
- `CloudSdkAppEngineInstances.disableDebug()`: indirectly calls `runAppCommand()`.
- `CloudSdkAppEngineLogs.read()`: indirectly calls `runAppCommand()`.
- `CloudSdkAppEngineServices.setTraffic()`: indirectly calls `runAppCommand()`.
- `CloudSdkAppEngineVersions.start()`: indirectly calls `runAppCommand()`.
- `CloudSdkAppEngineVersions.stop()`: indirectly calls `runAppCommand()`.
- `CloudSdkAppEngineVersions.delete()`: indirectly calls `runAppCommand()`.
- `CloudSdkAppEngineVersions.list()`: indirectly calls `runAppCommand()`.

(There might be more that I missed. And of course, there are more non-public methods.)

Documenting at least `CloudSdkNotFoundException` and `CloudSdkOutOfDateException` could be a good start for improving public Javadocs.

However, I imagine these methods as well as old and new methods will easily go out of sync because the exceptions are not checked exceptions.
