### ISSUE TITLE
Add env_var parameter to dev appserver

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/appengine-plugins-core#316]
Dev appserver now exposes --env_var for passing in environment variables

**Comment by patflynn** [comment]
@loosebazooka I don't understand how these variables are going to be used for Java Standard apps since they configure their environment variables via the appengine-web.xml.

**Comment by stickfigure** [comment]
@patflynn I wrote up a short explanation of why Java Standard apps need access to environment variables here: https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/150

**Comment by elharo** [comment]
This seems to have been done in https://github.com/GoogleCloudPlatform/appengine-plugins-core/commit/93567bd1932ae16e32d02a2a571824eb68aea653
