### ISSUE TITLE
cannot build on Mac

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-plugins-core#329]
Getting this error on my Mac from a fresh installation:

Failed tests:   testGetLocationFromLink_valid(com.google.cloud.tools.appengine.cloudsdk.PathResolverTest): expected:</[]var/folders/w7/xm3k6...> but was:</[private/]var/folders/w7/xm3k6...>

**Comment by ludoch** [comment]
Mac have this configuration for tmp files:
ls -lart /tmp
lrwxr-xr-x@ 1 root  wheel  11 Dec 14 10:34 /tmp -> private/tmp

**Comment by ludoch** [comment]
I'll provide a fix in a new PR.

**Comment by loosebazooka** [comment]
Weird, is that a general mac thing?

I guess we can resolve the directory before testing it.

**Comment by elharo** [comment]
all tests now passing on Mac
