### ISSUE TITLE
Is anyone using appengine-plugins-core/src/main/java/com/google/cloud/tools/appengine/api/services/

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#341]
I can't find any usages of appengine-plugins-core/src/main/java/com/google/cloud/tools/appengine/api/services/

Is this dead?

**Comment by elharo** [comment]
appengine-plugins-core/src/main/java/com/google/cloud/tools/appengine/api/logs/

and

appengine-plugins-core/src/main/java/com/google/cloud/tools/appengine/api/instances/

also look unused

**Comment by joaoandremartins** [comment]
I don't think we're using them in IntelliJ, that I wouldn't remove those branches either.
It seems like they could be useful in the future.

**Comment by elharo** [comment]
https://martinfowler.com/bliki/Yagni.html
