### ISSUE TITLE
Should we only copy app.yaml when doing flex staging?

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/appengine-plugins-core#347]
Right now we copy everything in the "appEngineDirectory" but we probably should only be copying the app.yaml, leaving the other configurations in SRC to be deployed by their respective commands?

@patflynn @elharo are you guys even using flex staging in intellij/eclipse?

**Comment by elharo** [comment]
@nbashirbello are we using flex staging in Eclipse?

**Comment by joaoandremartins** [comment]
This is our staging https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/master/google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/flexible/AppEngineFlexibleStage.java#L59

We just copy the app.yaml, Dockerfile (if runtime is custom) and the war/jar archive.

**Comment by nbashirbello** [comment]
@elharo yes, we are, doing what IntelliJ is doing.

**Comment by patflynn** [comment]
I didn't even know we had an appEngineDirectory param. We don't expose that
in any of our build tool UIs do we?

**Comment by loosebazooka** [comment]
We kind of do, but we default to src/main/appengine and don't really expect users to be customizing this.

**Comment by chanseokoh** [comment]
> @patflynn @elharo are you guys even using flex staging in intellij/eclipse?

We now use the flex staging support from appengine-plugins-core.

> Right now we copy everything in the "appEngineDirectory"

I don't think this is true. It's copying only `app.yaml`: https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStaging.java#L113

**Comment by chanseokoh** [comment]
FTR, #361.
