### ISSUE TITLE
Make javaHome a command parameter rather than a CloudSdk one

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/appengine-plugins-core#358]
Following https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/352, javaHome is now an argument of CloudSdk.Builder.
Since javaHome is only used on devappserver and standard staging, it should probably be a command parameter rather than CloudSdk's.

However, currently the model is, for example, for CloudSdkAppEngineDevAppServer to translate the RunConfiguration object into flags, and then CloudSdk runs the separate Java process.

We should find a way to provide javaHome in the *Configuration object, while staying true to the current model.
One way would be to not use CloudSdk for running devappserver or staging.

**Comment by JoeWang1127** [comment]
close as not planned
