### ISSUE TITLE
Flex Staging should only copy app.yaml out of appengineDirectory

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/appengine-plugins-core#361]
We don't need to copy the other yaml configs into the destination folder anymore.

**Comment by joaoandremartins** [comment]
Drive-by question: why not? Do they have to be individually specified?

**Comment by loosebazooka** [comment]
`deploy` doesn't deploy all of them anyway (only app), so there's no advantage to moving them around. The user can either use deployCron/Index/Queue... or just reference the actual file location in src/main/appengine
