### ISSUE TITLE
appYamls vs Services

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/appengine-plugins-core#367]
We should remove appYamls from devAppServer2 and just use services?

**Comment by akerekes** [comment]
remove `com.google.cloud.tools.appengine.api.devserver.RunConfiguration.getAppYamls()` and use com.google.cloud.tools.appengine.api.devserver.RunConfiguration.getServices()` instead

**Comment by joaoandremartins** [comment]
Maybe just make it very explicit in the Javadoc that services essentially boil down to app.yaml file pointers.

Also, since there is also the concept of a GAE service (which can contain many versions), I can't make up my mind on whether this is advisable.
