### ISSUE TITLE
Copy src/main/docker even w/o a custom runtime

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/appengine-plugins-core#374]
It would be nice if the contents of src/main/docker would get copied, even w/o a custom runtime.

@tswast FYI - care to comment on what you want?

**Comment by patflynn** [comment]
@meltsufin do the standard runtimes automatically add the entire contents of the staging directory to the image?

**Comment by meltsufin** [comment]
We only copy .war or .jar file, unless it's compat.
@aslo

**Comment by tswast** [comment]
Some examples of where this would be useful: Dropwizard  expect a YAML configuration file to be loaded from the file system, not as a JAR resource. I had to resort to custom runtimes to run the Dropwizard hello world.

My slightly weirder use case is that I was hoping to bundle a Linux binary file to use as an entrypoint.

**Comment by patflynn** [comment]
**if** we want to do this, it would have to start as a change to runtimes, and probably be something we'd want to do for all languages. @meltsufin looks like a discussion for the runtimes and app engine flex teams.

**Comment by tswast** [comment]
The Python runtime already copies everything into it, but that's probably a side-effect of it being a dynamic language.

**Comment by elharo** [comment]
@loosebazooka Is this still relevant?

**Comment by loosebazooka** [comment]
I have no idea. gonna close for now.
