### ISSUE TITLE
Set environment variables from appengine-web.xml for local run

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/appengine-plugins-core#377]
see https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1364 for some background.

The environment variables defined in appengine-web.xml are not being set on the process running devappserver1. 

One possible solution could be to parse appengine-web.xml for `<env-variables>` and set them when doing devappserver1 runs

**Comment by patflynn** [comment]
also https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/161
