### ISSUE TITLE
Working directory for spawned devappservers

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/appengine-plugins-core#385]
http://stackoverflow.com/a/43639428/1701388

We're not setting the working directory when launching the devappserver.

**Comment by chanseokoh** [comment]
#1864 closely related. I see this issue about setting the default working directory, while #1864 is a means to change that.

**Comment by chanseokoh** [comment]
Oops, I thought this was the Eclipse plugin repo.
