### ISSUE TITLE
Implement standard GAE staging

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/appengine-plugins-core#4]
We're currently depending on the App Engine SDK to stage standard GAE apps. (i.e., AppCfg.main()).

We should implement staging in the library, cutting the App Engine SDK dependency and also the SdkResolver one (which makes us set a system property with the GAE SDK root folder).

**Comment by patflynn** [comment]
@meltsufin here is the java library that supports standard staging:
https://mvnrepository.com/artifact/com.google.appengine/appengine-staging-sdk

**Comment by elharo** [comment]
That artifact lives in google3 and is currently abadonware.

**Comment by elharo** [comment]
see https://g3doc.corp.google.com/apphosting/g3doc/runtimes/java/maven_sdk.md?cl=head

**Comment by loosebazooka** [comment]
obsolete
