### ISSUE TITLE
CloudSdkAppEngineFlexibleStaging.stageFlexible() fails if app.yaml is malformed

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/appengine-plugins-core#406]
[Parsing malformed app.yaml here](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/v0.3.3/src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStaging.java#L82) using SnakeYAML will throw `ScannerException` and `ParserException` that are `RuntimeException`, as noted [here](https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/404/files).

I think the staging logic should just log a warning and continue staging rather than exploding, very much like it currently does with `IOException` on `app.yaml`.

**Comment by chanseokoh** [comment]
It may be rather right to fail staging. If so, we should throw `AppEngineException` as we currently do, e.g.,  when `app.yaml` or `Dockerfile` does not exist.

**Comment by patflynn** [comment]
I have to admit it makes me a bit nervous to duplicate the gcloud
validation in the core library. I don't want to break people when we
shouldn't.

**Comment by chanseokoh** [comment]
Failing when that app.yaml is inaccessible due to IO errors or when it is malformed is not semantic validation, so IMO it is okay. It should and will fail anyway at a certain point of the deploy pipiline.
