### ISSUE TITLE
Improve error - "The Google Cloud SDK could not be found in the customary locations and no path was provided" - please

### ISSUE THREAD

**Issue by paul-hammant** [GoogleCloudPlatform/appengine-plugins-core#416]
1. Customry locations could be detailed.
2. A URL could be included .. that talks of `install.sh` and `source ~/.bash_profile` etc.

**Comment by elharo** [comment]
Did you see this? It's an exception message that shouldn't be shown to an end user.

**Comment by paul-hammant** [comment]
Yes I saw it.  It wasn't a one off  - it was the persistent state of the deploy to appengine maven target

 I solved it by rerunning install.sh and then sourcing the ./bash_profile.

**Comment by elharo** [comment]
That sounds like an RFE for the Maven plugin then. This library does not consider itself to talk directly to the end user.

**Comment by paul-hammant** [comment]
You know the maven plugin - https://github.com/GoogleCloudPlatform/gcloud-maven-plugin - doesn't have issues or pull-requests turned on :(

**Comment by patflynn** [comment]
https://github.com/GoogleCloudPlatform/app-maven-plugin

**Comment by paul-hammant** [comment]
Thanks Pat.

**Comment by CrisRys** [comment]
I'm encountering this messages.   Is there an environmental variable that is supposed to point at the path of the The Google Cloud SDK ?      What is considered a "customary location"?

**Comment by CrisRys** [comment]
The link below has a comment by  hemanthk92 on Oct 9 that provided a workaround for me on this issue, but I'm still not clear on what is configured incorrectly that I required the workaround.
https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/190

**Comment by chanseokoh** [comment]
@CrisRys the Maven (as well as Gradle/IntelliJ/Eclipse) plugin wants to run the `gcloud` binary. It needs to know where the binary is.

If the `gcloud` binary is on your `$PATH`, the plugin will have no problem executing it. So, one workaround is to add the `bin` directory of your Cloud SDK to your `$PATH`.

The plugin will also look for some well-known customary locations. For example on Linux,
- `$HOME/google-cloud-sdk`. So, another workaround could be to create a symlink of `$HOME/google-cloud-sdk` pointing to your actual Cloud SDK install location. Alternatively, you could move your actual install location to `$HOME/google-cloud-sdk`.
- Where package managers (e.g., apt, yum etc.) install Cloud SDK, which will vary between platforms. (`/usr/lib/google-cloud-sdk`, `/google/google-cloud-sdk`, `/usr/local/share/google/google-cloud-sdk`, etc.)

You can also set `$GOOGLE_CLOUD_SDK_HOME` to point to your install location.

Looks like `-DcloudSdkPath` works for the Maven plugin too.

For IntelliJ/Eclipse plugins, they will additionally have their own UI to set the Cloud SDK path.

**Comment by elharo** [comment]
FYI, the first release of 2018 should provide its own Cloud SDK and make all this moot.

**Comment by CrisRys** [comment]
This is odd, **gcloud** is in my $PATH,  as I can execute gcloud from command line, but not found by **whereis** or **which** commands,  here are some example commands and output:

```
Criss-Retina-2:helloworld cris$ echo $PATH
~/Documents/Development/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
Criss-Retina-2:helloworld cris$ gcloud version
Google Cloud SDK 182.0.0
app-engine-java 1.9.59
app-engine-python 1.9.63
bq 2.0.27
core 2017.12.01
gsutil 4.28
Criss-Retina-2:helloworld cris$ which gcloud
Criss-Retina-2:helloworld cris$ whereis gcloud
Criss-Retina-2:helloworld cris$ find ~/documents/Development/google-cloud-sdk/bin -name gcloud
/Users/cris/documents/Development/google-cloud-sdk/bin/gcloud

```

**Comment by CrisRys** [comment]
Thanks @chanseokoh .   I ended up setting   `$GOOGLE_CLOUD_SDK_HOME `

**Comment by chanseokoh** [comment]
`~` is a shell expansion (https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html). Non-shell programs, such as ours, won't expand it to $HOME. Try setting an absolute path in $PATH.

**Comment by nlaney** [comment]
I ended up moving google-cloud-sdk to $HOME using eclipse 4.7.1a. Overall the migration from gradle-appengine-plugin wasn't too bad. Missed a few steps, like where to install gradle-appengine-plugin, but no worries, it's running now. Totally worth it for hot swapping and datastore persistence in devserver, biggest time wasters of all. Thanks for all the great work?

**Comment by Georgian** [comment]
If you get this when running the gradle "appengineDeploy" task, you can add this to you build.gradle:

```
appengine {  // App Engine tasks configuration
	tools.cloudSdkHome="gcloud-sdk-path"
}
```

Where ```gcloud-sdk-path``` is found (if you don't know it by heart) by running ```$(gcloud --form at='value(installation.sdk_root)' info)``` in the terminal. 

Documentation here: [https://cloud.google.com/appengine/docs/flexible/java/gradle-reference#global_properties](https://cloud.google.com/appengine/docs/flexible/java/gradle-reference#global_properties)

**Comment by unomonteiro** [comment]
> $(gcloud --form at='value(installation.sdk_root)' info)
> $(gcloud --format='value(installation.sdk_root)' info)

**Comment by luan-nvg** [comment]
> GOOGLE_CLOUD_SDK_HOME

solved my problem thank you very much

**Comment by luan-nvg** [comment]
> Thanks @chanseokoh . I ended up setting `$GOOGLE_CLOUD_SDK_HOME `

solved my problem thank you very much
