### ISSUE TITLE
Fail gracefully when windows path has quotes or is otherwise invalid

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/appengine-plugins-core#427]
Apparently windows paths are allowed to have `"` in them, see https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/199

We probably need to ~~fail~~ ignore this a little more gracefully in https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/src/main/java/com/google/cloud/tools/appengine/cloudsdk/PathResolver.java

**Comment by patflynn** [comment]
I think the actual bug is that we should not let a bad path entry in the
path stop the search.

Ideally we would log a warning when the path entry is invalid though.

**Comment by chanseokoh** [comment]
> Apparently windows paths are allowed to have `"` in them

Yes, AFAIK, a path containing `"` such as `"C:\Users\DPE Admin\Downloads\apache-maven-3.5.0\bin"\gcloud` could be a valid path on Windows. It's not a bad path, so why do we want to fail in this case?

**Comment by loosebazooka** [comment]
I believe I used "fail" incorrectly, but path.get seems to throw an exception.

**Comment by elharo** [comment]
I'll have to check but I believe the path is invalid. I.e. Windows paths may not contain a double quote. However as @patflynn says we can handle this more gracefully.

**Comment by elharo** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx confirms that the quote is not legal in Windows paths.

**Comment by chanseokoh** [comment]
The doc says you can't create a directory name or a file name containing a quote, which is pretty much expected. However, the situation is that we have quoting in describing a path (e.g., `C:\"Program Files (x86)"\common\`), and it's not clear how this should be handled in this context or if it's a client's fault that did not removed the quotes. (Windows application won't have problems interpreting this path string.)

What is important, I think, is that Windows seems to naturally put quotes when defining path environment variables as @lesv said (https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/199#issuecomment-311469590), so many users might face the same situation. But it's still not clear if it is a fault of some upper layer that should have stripped out the quotes.

**Comment by elharo** [comment]
In context this comes directly from the PATH environment variable. Until proven otherwise, I believe this environment variable should not contain quotes. If it does, that's simply an uncommon config error.

**Comment by chanseokoh** [comment]
@lesv, are you sure setting an env variable on Windows using the _Browse..._ button puts quotes? In my Windows testing (Windows Server 2016) on GCE, it doesn't put quotes. If it still does, which version do you use?

**Comment by lesv** [comment]
It did - Windows 10.

**Comment by lesv** [comment]
(I sure didn't put it there)

**Comment by elharo** [comment]
Can someone find definitive Windows docs on this? It sounds very strange.

**Comment by lesv** [comment]
Note - the fact I saw the double quotes in when setting the path doesn't mean that it put it there on the result.  I also tried removing the quotes with edit, and I continued to get the same error message.

**Comment by lesv** [comment]
I'm suspecting that whatever is used to split the PATH might be adding the quotes in.

**Comment by elharo** [comment]
FYI: not normative but suggestive nonetheless: https://stackoverflow.com/questions/34669912/quotes-in-windows-environment-variable-value

**Comment by elharo** [comment]
and https://serverfault.com/questions/349179/path-variable-and-quotation-marks-windows

**Comment by lesv** [comment]
Eliott,  I think your going about this backwards.

I just followed a simple process to add a path.  It gave me something that broke our code.  Even if Microsoft isn't conforming to it's docs, it still a reasonable path for me to have followed, our users are likely to also experience this.

**Comment by chanseokoh** [comment]
> In my Windows testing (Windows Server 2016) on GCE, it doesn't put quotes.

Okay, it didn't put quotes when I was modifying a user PATH env var, but I can see that it does put quotes when modifying the system PATH env var:

![selection_001](https://user-images.githubusercontent.com/10523105/27618870-b9376f92-5b8c-11e7-9815-1e4a8fde29b3.png)

The env variable does contain quotes for my new entry `...;"C:\Users\chanseok\Desktop\New folder";...` as below:
```
C:\Users\chanseok\Desktop\appengine-plugins-core>echo %PATH%
C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\GooGet;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Compute Engine\sysprep;C:\Program Files\Google\Compute Engine\sysprep\;C:\Program Files\Google\Compute Engine\metadata_scripts\;"C:\Users\chanseok\Desktop\New folder";C:\Users\chanseok\AppData\Local\Microsoft\WindowsApps;;
```

Then I can reproduce this problem (`mvnw package` is enough to trigger this):
```
Tests run: 5, Failures: 0, Errors: 1, Skipped: 3, Time elapsed: 0.015 sec <<< FAILURE!
testResolve(com.google.cloud.tools.appengine.cloudsdk.PathResolverTest)  Time elapsed: 0.015 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Users\chanseok\Desktop\New folder"\gcloud
```

What is funny is that, the second time I open the PATH env editor, the editor doesn't show the quotes.

**Comment by elharo** [comment]
I'd still like to see normative docs on Windows environment variables so we know how to properly parse this, and what other problems might be lurking. Maybe @csells knows?
