### ISSUE TITLE
Should CloudSDK validation be coupled with jdk validation?

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/appengine-plugins-core#441]
[CloudSdk#validateCloudSdk](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/713bff4c658b62640345e6312f59089c0e2c3437/src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java#L469) also validates that the system jdk points to a proper executable. 

Should these be coupled like this? This causes all validation of the CloudSDK to fail on improper jdk config. Presumably not all usages of the SDK require this.

**Comment by etanshaul** [comment]
never mind - I guess its needed both for devappserver runs and staging - see https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/352

**Comment by patflynn** [comment]
Ideally I would separate java sdk validation from cloud sdk validation.  Typically I would expect the running (IJ or Maven) to take responsibility for displaying an appropriate error if the java sdk is incorrectly configured.

**Comment by etanshaul** [comment]
yea. what do you think then about just removing the jdk check completely from this library like we discussed offline. 

Like you said, it should be up to the clients (IJ for instance doesn't really need this validation since the actions that require the cloud sdk also already require a configured project jdk)?

**Comment by patflynn** [comment]
I'm OK with this.
