### ISSUE TITLE
Add toggle for appending or replacing the environment

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/appengine-plugins-core#446]
Eclipse's standard environment variables UI offers support for either appending values to the inherited environment (appengine-plugins-core's current behaviour) or replacing the environment (clean-room).  The _replace_ option is useful to ensure no inherited values bleed through.

It could be argued that appengine-plugins-core should default to _replace_ to best mimic the App Engine platform.

**Comment by briandealwis** [comment]
Apps run on devappserver1 currently inherit the environment.  Whereas devappserver2 provides an `—env_var` flag, and replaces the environment except for `PATH`.  When I run locally (on MacOS), I see:
```
APPLICATION_ID=dev~None
JAVA_MAIN_CLASS_10593=com.google.appengine.tools.development.devappserver2.StandaloneInstance
PATH=/Users/bsd/bin/Darwin:/Users/bsd/bin:/usr/local/bin:/Users/bsd/Manumitting/Projects/P2/scripts:/opt/pkg/bin:/usr/bin:/bin:/opt/pkg/sbin:/usr/sbin:/sbin:/etc:/opt/vagrant/bin:/Users/bsd/research/bin:/usr/local/installs/ec2-api-tools-1.3-57419/bin
PWD=/Users/bsd/Manumitting/Projects/GooglePluginEclipse/runtime-gcloud-CLEAR/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/test-aes7-bigquery
SDKROOT=/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine
TZ=UTC
USER=bsd
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x52
```

**Comment by JoeWang1127** [comment]
close as not planned
