### ISSUE TITLE
CloudSdkVersion --> SemanticVersion

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#459]
Convert CloudSdkVersion to a general SemanticVersion class. There's nothing here specific to the Cloud SDK and CT4E needs this for non-CloudSDK versions.

**Comment by patflynn** [comment]
I don't think that CloudSdkVersion is semantic.

**Comment by chanseokoh** [comment]
Maybe that's true. Then the class should update its Javadoc and rename methods (e.g., `getSemVerRegex()`) and fields.

```java
/**
 * Version of the Cloud SDK, which follows the <a href="http://semver.org/spec/v2.0.0.html">Semantic
 * Version 2.0.0 spec</a>.
 */
public class CloudSdkVersion implements Comparable<CloudSdkVersion> {

  private static final Pattern SEMVER_PATTERN = Pattern.compile(getSemVerRegex());
```

**Comment by briandealwis** [comment]
> CT4E needs this for non-CloudSDK versions

`org.osgi.framework.Version`?

**Comment by elharo** [comment]
@patflynn How does this class vary from the semantic ver spec?

**Comment by patflynn** [comment]
I don't know how this class varies, but I'm just pointing out that the Cloud SDK versioning scheme is not based on semantic versioning.

**Comment by lqiu96** [comment]
Closing as part of cleanup. Please re-open if it's still relevant
