### ISSUE TITLE
Add service account role to the client lib metadata

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/appengine-plugins-core#485]
Some APIs can be used with a service account with no role. For example, the translate API. 

Others (those that access project data) require a role to be set: GCS, Datastore etc.

I am proposing to add metadata to the library json that contains the minimum admin role that is needed for a given API. For example:
- GCS - > "Storage Admin"
- Datastore -> "Cloud Datastore Owner"

The consumers of this metadata could then decide to use (or not to use) this info. 

The complication with this proposed approach is with projects that consume multiple APIs. The service account then needs the union of all of these individual roles.

**Comment by etanshaul** [comment]
@patflynn, @elharo  -  what do you guys thing about this?

The other option is to not include this information and the consumers would just set all service accounts to "Project Editor". 

It could get complicated when trying to make a single service account work with multiple APIs.

**Comment by elharo** [comment]
Which way does it get complicated when trying to make a single service account work with multiple APIs? When we use "project Editor" or when we use individual roles?

**Comment by etanshaul** [comment]
I meant that it is a bit more complication if we use granular roles. For example, say a project is using both to GCS and to datastore. The service account would need to contain both the GCS admin role and the datastore owner role. 

But like I said, the choice to use these roles can be left up to the consumer.

**Comment by etanshaul** [comment]
Update on this:

We determined that correct approach here is in fact to use granular roles.

Therefore, we need a place to store this metadata (the mapping from client-lib to set of roles). 

@elharo, you voiced some concern about mixing these two concepts (the client lib metadata and cloud API metadata). On second look at libraries.json, this distinction is a bit murky to me - the client libraries are in a way tightly coupled to the API they are meant for. Do you still think there is a useful distinction here (enough to prevent us from adding the role metadata to this file)?

**Comment by elharo** [comment]
I think it probably could go in libraries.json, just not in the clients section. 

My gut is to list all the roles. I'm not sure what the "the minimum admin role" is, or whether that's something we want to depend on. Pantheon gives the user the choice of which roles to enable and I'm not sure we should hide that.

**Comment by etanshaul** [comment]
Yeah - I abandoned "minimum admin role" concept. See the PR for this.
