### ISSUE TITLE
Check if minimum cloud SDK version needs to be bumped

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/appengine-plugins-core#492]
We noticed some errors deploying to App Engine standard with a version of gcloud that was not flagged by the min version check. Perhaps it needs to be updated.

**Comment by nbashirbello** [comment]
Current gcloud min version is 171.0.0 (https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java)

**Comment by nbashirbello** [comment]
Downgrading to gcloud version 171.0.0 works. Could error be caused by lower app engine version?

**Comment by etanshaul** [comment]
I thought that the App Engine java component was co-upgraded/downgraded alongside the cloud sdk. 

WHen you do “gcloud —version” does it show an updated appengine-java component?

**Comment by nbashirbello** [comment]
Google Cloud SDK 179.0.0/app-engine-java 1.9.59

Google Cloud SDK 171.0.0/app-engine-java 1.9.55

**Comment by etanshaul** [comment]
Maybe we have a broken min version check in IntelliJ. I’m not sure how else to explain it.

**Comment by etanshaul** [comment]
closing as I'm also not able to reproduce:

- the min version check is working as expected
- the current min version (171.0.0) still works

@nbashirbello If you ever get to the bottom of the issue you were having, feel free to re-open this / open a new one
