### ISSUE TITLE
usage question because of the readme

### ISSUE THREAD

**Issue by schmitch** [GoogleCloudPlatform/appengine-plugins-core#507]
Hello, currently I have a question because of the statement inside the readme:

> IMPORTANT: This library is used by Google internal plugin development teams to share App Engine related code. It's use for any other purpose is highly discouraged and unsupported. Visit our App Engine documentation for more information on Google supported clients for App Engine administration.

At the moment I actually try to create a new [sbt](http://www.scala-sbt.org/) client for appengine which also supports the [playframework](https://www.playframework.com/) to actually make use of the plugin I used the `appengine-plugins-core` dependency. (https://github.com/schmitch/play-appengine)

Is there anything I need to know while using this repository?
Or does this sentence just mean that this has not a stable api and every version could break it?
How can I interpret this notice?

Because actually using this code makes it super simple to create a client for appengine especially under the sbt build tool.

**Comment by elharo** [comment]
It is definitely not stable. We break the API almost every release. 

But it's a little worse than that. Assume this repo can disappear overnight and plan accordingly. I wouldn't use it unless I had forked the version of the repo I depended on and was able to maintain the fork myself.
