### ISSUE TITLE
Better progress monitoring for managed SDK operations

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/appengine-plugins-core#519]
Latest iteration of the progress listener interface with child/subtask in it. 

Key changes : 
- workDone is now *not* cumulative.
- allow child-progressListeners. 
  - ProgressListener no long need to know any state except their own.
  - `normalizedProgress = currentProgress * allocation/totalWork`

```
public interface ProgressListener {
  void start(String message, long totalWork);
  void update(long workDone); // not cumulative
  void done();
  ProgressListener newChild(long allocation);
}
```

an example implementation would look something like this : 
```java
 public static class ParentListener implements ProgressListener {

    private final long totalWorkDone = 0;

    @Override
    public void start(String message, long totalWork) {
      SystemProgressBar.setMessage(message);
    }

    @Override
    public void update(long workDone) {
      totalWorkDone += workDone;
      SystemProgressBar.setWorkDone(totalWorkDone);
    }

    // this is not part of the progress api, but a convenience of this implementation
    public void update(String message) {
      SystemProgressBar.setMessage(message);
    }

    @Override
    public void done() {
      SystemProgressBar.done()
    }

    @Override
    public ProgressListener newChild(long allocation) {
      return new ChildListener(allocation, this);
    }
  }

  public static class ChildListener implements ProgressListener {

    private final long allocation;
    private final ParentListener parent;

    private long totalWork;
    private long totalWorkDone = 0;
    private long lastUpdate = 0;

    public ChildListener(long allocation, ParentListener parent) {
      this.allocation = allocation;
      this.parent = parent;
    }

    @Override
    public void start(String message, long totalWork) {
      this.totalWork = totalWork;
      parent.update(message);
    }

    @Override
    public void update(long workDone) {
      totalWorkDone += workDone;
      long normalizedtotalWorkDone = totalWorkDone * allocation / totalWork;

      if(normalizedtotalWorkDone > lastUpdate) {
        parent.update(normalizedtotalWorkDone - lastUpdate);
        lastUpdate = normalizedtotalWorkDone;
      }
    }

    @Override
    public void done() {
      parent.update(allocation - normalizedTotalWorkDone);
    }

    @Override
    public ProgressListener newChild(long allocation) {
      return null; // or whatever
    }
  }

}
```

**Comment by loosebazooka** [comment]
@briandealwis Would this work with the eclipse progress monitoring?
@ivanporty Could this work with the intellij progress monitoring?

**Comment by ivanporty** [comment]
What would be the `Console` in 
```java
  // console out
  Console newConsole();
```

it is another interface or JDK Console, what's the intention?

Can you please clarify a bit on 
> cloud SDK action can spawn multiple progress bars?

**Comment by loosebazooka** [comment]
@ivanporty oops that was old, I updated it.

**Comment by briandealwis** [comment]
That won't work on Eclipse very easily, unless a `FeedbackHandler` is provided on each action: our code cannot create `IProgressMonitor`s — rather we request that the Eclipse platform execute some code (there are a few different mechanisms), and the platform provides that code an `IProgressMonitor` to report its progress.  For example, here's how we'd likely trigger an update-SDK action in Eclipse:

```
// Job is like an Eclipse-managed thread
Job updateInstallationJob = new Job("Updating Cloud SDK") {
  public IStatus run(IProgressMonitor monitor) {
    ManagedCloudSdk sdk = ManagedCloudSdk.newManagedSdk();
    try {
      sdk.newUpdater().update(new EclipseFeedbackHandler(monitor));
      return Status.OK_STATUS;
    } catch(SomeKindOfException ex) {
      return new Status(IStatus.ERROR, …, "Unable to update installation", ex);
    }
  }
}
```

We can map multiple calls to `newProgressBar()` to create child monitors of the original monitor.

I'm a bit leery about the logging aspects.  Are you thinking that we would map these to whatever logging implementation we're using?  Or are these logging aspects more for reporting messages to the UI?  I expected more of a `reportError()` or `reportInfo()`. Or a status object from the call.

**Comment by loosebazooka** [comment]
I haven't really thought out the logging stuff in any detail, but they're for tying into whatever logging implementation the platform is using.

Okay, so we probably have to do a single progress bar? Maybe it can provide sufficient information to handle the ide single progress case and the console multiprogress case.

Eclipse can't "reset" a progress bar can it?

Would you expect install to look like this?
Where downloading shows progress up to 1/3 of the bar and extracting and installing are almost "static" in that they don't show progress but just move to the half way point of their third of the progress bar until finished.
```
#===============================# // full bar for reference
Downloading
#=
#==
#=====
#=========
Extracting (moves to 3/6th of bar)
#==================
Installing (moves to 5/6th of bar)
#==========================
done
#===============================#
```

**Comment by chanseokoh** [comment]
This may be a different point of view from @briandealwis, but in Eclipse, I am thinking of the following two different kinds of progress reporting regarding the Cloud SDK.

- Eclipse message console: this is the case for App engine local run and deploy. In this case, we simply redirect whatever plain text output appengine-plugins-core (such as #518) or gcloud dumps in detail. For example, we are already redirecting output of dev appserver and gcloud app deploy. We just do the same for gcloud install. I think text output is good and OK in this case.
- Single progress bar: this is for background update and install. Will be implemented as an Eclipse job. Due to the Eclipse job UI limitation, we can't redirect detailed gcloud install/update text output, unless we devise our own install UI. What we can do at best is to show is the name of the main action and sub-actions, and increment the ticks of the UI progress bar.

Eclipse can reset a progress bar, in the abstract sense. I mean, a sub-action can think of getting a fresh new progress bar.

**Comment by briandealwis** [comment]
Within a Job, Eclipse offers us only a single progress monitor.  We can split that progress monitor into multiple sections by creating sub-monitors which are given them some ticks from their parent.  For example, to do the install with `app-engine-java` we might do something like the following:
```java
Job installationJob = new Job("Installing Google Cloud SDK with Java support for App Engine") {
  public IStatus run(IProgressMonitor monitor) {
    ManagedCloudSdk sdk = ManagedCloudSdk.newManagedSdk();
    try {
      SubMonitor progress = SubMonitor.convert(monitor, 50); // 50 = 40 + 10
      if(!sdk.isInstalled()) {
        sdk.newInstaller().install(new EclipseFeedbackHandler(progress.newChild(40)); 
      }
      sdk.newComponentInstaller().installComponent(SdkComponent.APP_ENGINE_JAVA,
          new EclipseFeedbackHandler(progress.newChild(10)); 
      return Status.OK_STATUS;
    } catch(SomeKindOfException ex) {
      return new Status(IStatus.ERROR, …, "Unable to install the Google Cloud SDK", ex);
    }
  }
}
```
You'd call `newProgressBar()` within each of the downloading, extracting, and installing phases, which we'd turn into creating a new child of the SubMonitor, and we'd pass the `ProgressBar#start(message, totalAmount)` to our `beginTask(message, totalAmount)`.

For us, the progress would be reflected in the progress area in the window status bar, or the _Progress_ view.

My 2¢ w.r.t. logging: rather than inventing yet another logging facade either use slf4j or java.util.logging.  I'm pretty sure Maven and Gradle provide their own configurations for both.

**Comment by ivanporty** [comment]
In IntelliJ, when you run a background task, you can update the progress bar with a text and a done percentage. Technically it probably doesn't make sense to start a new background process when `newProgressBar()` is called, but we can just change the text and reset the percentage to 0. We can keep the single percentage for all work but we need to work total amount of work across all tasks then.

**Comment by briandealwis** [comment]
Oh right, Eclipse can't reset the progress: the `IProgressMonitors` only accumulate increments of work

**Comment by loosebazooka** [comment]
So would it be okay to have newProgress()? for both intellij and eclipse? Would it be okay to have the IDE accept the responsibility of calculating and normalizing all the progress?

**Comment by briandealwis** [comment]
Given my druthers, I'd rather have `ProgressBar#newChild()` instead of this factory-style `newProgressBar()` method.  But providing we're systematic in calling `done()` we should be able to manage these sub-progress bars with a stack.

**Comment by elharo** [comment]
This probably shouldn't assume the existence of a console or a console monitor. Even where it exists, it's at best a weak hack to try to shoehorn a command line program into a GUI.

**Comment by loosebazooka** [comment]
@briandealwis @ivanporty, updated description, I'm not super keen on this solution though. Would it work in the IDE?

**Comment by loosebazooka** [comment]
I think I might just deal with this in the library, and have a single progress handler.

```
interface FeedbackHandler {
  void startProgress(String message, long totalWork);
  void updateProgress(String message);
  void updateProgress(long workDone);
  void finishProgress();

  // console out
  void console(String rawMessage)

  // Logging
  Logger getLogger()
}
```

**Comment by ivanporty** [comment]
Feels very Eclipse specific, I don't think we have the same concept of child progress/jobs in IntelliJ, at least I haven't seen such API, just straightforward direct progress bar reporting.

**Comment by ivanporty** [comment]
I like the new iteration better. BTW, what's the `Logger`? Is it SLF4J?

**Comment by ivanporty** [comment]
With the updated interface, when do we know the overall process is done? `workDone == totalWork` or `finishProgress`?

**Comment by loosebazooka** [comment]
I mean if all the math is right, workDone == totalWork should immediately follow a finishProgress. But finishProgress is probably going to be the end of the progress.

**Comment by loosebazooka** [comment]
`Logger` is probably going to be a `java.util.logging.Logger`

**Comment by briandealwis** [comment]
I prefer the single-level interface in https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/519#issuecomment-361391231.  I'd avoid exposing the logging implementation though — it feels weird to use someone else's logger.

**Comment by ivanporty** [comment]
To avoid dealing with Loggers, how about just exposing something like `void log(level, message)` for both log/console (console being INFO messages). Level can probably be re-used from java.util.logging?

**Comment by loosebazooka** [comment]
I think I previously used java.util.logging directly in the classes that did logging. 

It came up that we wanted finer grained controls on logging coming from libraries, but I guess a user could just set that in their logging.properties.

But we could also just use Ivan's suggestion.

Console progress is useful when we're providing passthough of cloud sdk progress which then requires us to use bytes instead of lines (since it outputs multiple times on the same line to indicate progress). For something like running install.sh, the user could look at the console to see where the cloud sdk install is going.

**Comment by loosebazooka** [comment]
@ivanporty @briandealwis updated main comment on this thread. Let me know if that works for you.

**Comment by briandealwis** [comment]
```java
interface ProgressHandler {
  void start(String message, int totalWork)
  void update(String message)
  void update(String workCompleteSoFar)
  void done()
}
```
Should that second `update()` take an `int`?  Looks good to me.

**Comment by ivanporty** [comment]
Yes, looks good. I assume `ProgressHandler.update(String)` will receive different messages from `ConsoleListener.console(String)`, no duplicates?

**Comment by loosebazooka** [comment]
Yes, the progress updater will be pretty simple, just a subtask name or something like that. For instance, 
sdkInstaller.install() will produce 3 such messages :+1: 
- downloading blah blah
- extracting blah blah
- installing blah blah

**Comment by loosebazooka** [comment]
@briandealwis @ivanporty , there's some cost to this newest implementation on the implementer, but it does appear to be mostly mimicking the eclipse mechanism, and once implemented the progressListener is pretty standard.
