### ISSUE TITLE
Locking the Managed Cloud SDK

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#527]
Figure out how we lock the managed Cloud SDK to prevent updates while a deploy or local run is occurring and vice versa.

Probably needs a lock file of some kind since the lock is shared across different tools in different processes. 

Related: https://b.corp.google.com/issues/72654481

**Comment by chanseokoh** [comment]
So, for example, whenever someone instantiated a `CloudSdk` instance (doesn't have to be precisely at this location though), we place a read lock, and any attempts to update the managed SDK from any tool are prevented or blocked. However, with the read lock, it is OK for other tools to still instantiate and use a `CloudSdk`.

The other direction is that, if any tool started an install/update, we place a write lock. Any tools who attempt to install/update the SDK or instantiate a `CloudSdk` are prevented or blocked.

As a note, https://issuetracker.google.com/issues/72654481 is a bit relevant. However, I'm not sure if this can be handled best at the Cloud SDK-level.

**Comment by JoeWang1127** [comment]
close as not planned
