### ISSUE TITLE
CloudSdkDevAppServer1 does not terminate on misconfigured servlets

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/appengine-plugins-core#530]
A misconfigured app (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1964) or servlet (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2771) will lead to a devappserver1 cannot be terminated by sending `/_ah/admin/quit`.

In this situation, we need to terminate the process.  But `CloudSdkDevAppServer1` doesn't actually maintain any state about the launched server.  Somewhat oddly, we need to pass in the devappserver host and port to `stop(StopConfiguration)` even though the instance was provided that information on `start(StartConfiguration)`.

Looking at the CT4E's implementation, we're actually managing a lot of state that seems better suited for the `CloudSdkDevAppServer{1,2}` implementations, such parsing server output to:

  - detect server state (starting, started, stopping, stopped)
  - detecting the server and admin ports
  - determining the service/module serving ports
  - turning `/_ah/admin/quit` failure into process termination

**Comment by chanseokoh** [comment]
> Somewhat oddly, we need to pass in the devappserver host and port to stop(StopConfiguration) even though the instance was provided that information on start(StartConfiguration).
>
> Looking at the CT4E's implementation, we're actually managing a lot of state that seems better suited for the CloudSdkDevAppServer{1,2} implementations, such parsing server output to:

I think the current stateless model makes sense for non-interactive command-line build tools.

> turning /_ah/admin/quit failure into process termination

So, for example, it'll be difficult to kill a dev appserver process from another process (Maven plugin invocation) that did not create it.

**Comment by lqiu96** [comment]
Closing as part of cleanup. Please re-open if it's still relevant
