### ISSUE TITLE
Store managed SDK in more appropriate locations

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/appengine-plugins-core#534]
The managed Cloud SDK  currently installed the SDK in ~/.google-cloud-tools-java, which is contra to the guidance from the various OS specs. 

The [XDG basedir spec](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) would seem to guide using the $XDG_CACHE_HOME (e.g., `~/.cache/google-cloud-tools-java`). 
On MacOS  we should use something like `~/Library/Application Support/`and  on Windows `%LOCALAPPDATA%` (I think).

**Comment by loosebazooka** [comment]
Just to hash this out a little:

The code might look like this:
```java
Path getSdkCacheDir() {
  Path userHome = Paths.get(System.getProperty("user.home"));
  Path cloudSdkPartialPath = Paths.get("google-cloud-tools-java").resolve("managed-cloud-sdk");

  // https://developer.apple.com/library/content/qa/qa1170/_index.html
  if (os == MAC) {
     return userHome.resovle("Library").resolve("Application Support").resolve(cloudSdkPartialPath);
     // maybe a check to see if this directory exists?
  }
  // I can't find any good docs on this, but this seems to pop up sometimes, but it's APPDATA vs LOCALAPPDATA, and we will chose LOCALAPPDATA?
  if (os == WIN) {
    String localAppDataDir = System.getEnv("LOCALAPPDATA");
    if (localAppDataDir.isNullOrEmpty()) { 
      throw someException; 
    }
    return Paths.get(localAppDataDir).resolve(cloudSdkPartialPath);
  }

  if (os == NIX) {
    return userHome.resolve(".cache").resolve(cloudSdkPartialPath)
  }
}
```

**Comment by loosebazooka** [comment]
@ivanporty @briandealwis how does this look?

**Comment by elharo** [comment]
should work

**Comment by briandealwis** [comment]
LGTM.

https://superuser.com/questions/21458/why-are-there-directories-called-local-locallow-and-roaming-under-users-user

`APPDATA` is part of the user's profile and will roam (copied to the network).
`LOCALAPPDATA` is just for the user's machine.

So I think `LOCALAPPDATA` is the right one.

**Comment by ivanporty** [comment]
No objections

**Comment by briandealwis** [comment]
I should have added reference for macOS / MacOS X: https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html
