### ISSUE TITLE
Move to java8...

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/appengine-plugins-core#539]
Make appengine-plugins-core build and target Java 8.

I believe all our tools can now be moved?
@elharo ?
@etanshaul ?

**Comment by elharo** [comment]
Eclipse is good to go

**Comment by etanshaul** [comment]
good on on the IntelliJ side too

**Comment by patflynn** [comment]
Shouldn't this wait until App Engine Java 7 runtime deprecation?

Let's talk about this in the weekly.

**Comment by elharo** [comment]
The Java 7 runtime is already deprecated: https://cloud.google.com/appengine/docs/standard/java/runtime

But either way, that doesn't matter here. This is only about what VM our client tools run with. You can still deploy a Java 7 app with this.

**Comment by patflynn** [comment]
I totally forgot that happened already.

Carry on.
