### ISSUE TITLE
Format bytes into human readable number for ProgressListener

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/appengine-plugins-core#542]
When using `ProgressListener`, Managed SDK download process calls it with unformatted long bytes numbers, inconvenient to read, i.e.:

![sdk-download](https://user-images.githubusercontent.com/11686100/36606646-5bf0027c-1892-11e8-92b0-5b81f9130cf5.png)

Would be great to have them formatted in locale-sensitive manner using standard Kb/Mb notations.

**Comment by loosebazooka** [comment]
Yeah brian asked about this too, I guess it's time to fix it.

**Comment by TadCordle** [comment]
@ivanporty Could you explain what you mean by "locale-sensitive"?

**Comment by briandealwis** [comment]
Different locales (languages, regions) represent numbers differently.  For example, the separator used for separating thousands, millions.  In this case, the "kb" or "mb" may need some other term in other languages.

**Comment by loosebazooka** [comment]
I don't know if we should put too much behind making this change include locale specific output. Perhaps our number formatter could use the configured Locale, but configuring for kB and MB might not be worth it given our general lack of coverage on this matter.

@ivanporty are you mostly concerned about the number format?

**Comment by ivanporty** [comment]
@loosebazooka yes, mostly about way to represent the number itself
