### ISSUE TITLE
Update Guava to 21.0 (not 24.0-jre)

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/appengine-plugins-core#548]
@etanshaul what version of guava is released with intellij? We don't want to set this too incompatible with intellij or we'll end up with some method missing exceptions if intellij loads in an older version of guava.

@elharo eclipse is presumably safe from these kinds of issues because of osgi?

**Comment by etanshaul** [comment]
idea 2017.3 brings in guava 21

**Comment by etanshaul** [comment]
unfortunately even the current EAP (2018.1) also brings in v21. I don't know off hand what problems using guava 24 here will introduce, but I expect there to be some incompatibility.

**Comment by elharo** [comment]
Eclipse could likely now move to Guava 21 with adequate warning. 24.0 might or might not be possible. I'd have to check.

**Comment by loosebazooka** [comment]
Alright, lets go to 21, then.

**Comment by elharo** [comment]
Might want to check google-cloud-java as well. Some of their stuff relies on Java 7 so they may need 20.0 or earlier.

Also, does ide-login use Guava?

**Comment by loosebazooka** [comment]
What's our connection with google-cloud-java from a compile time perspective?

**Comment by loosebazooka** [comment]
Presumably the ide-login repository will have to be updated, it's at guava 20, but if eclipse is using java8 already, it probably should be updated. Dependency convergence in maven should pick this up though.
