### ISSUE TITLE
Managed Cloud SDK installation requires python

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/appengine-plugins-core#551]
Trying to install the Managed Cloud SDK on a fresh Windows box fails as the installation requires Python.  Here's what we see on our console:
```
Installing/upgrading the Cloud SDK... (may take several minutes)
[Installing Google Cloud SDK]
Welcome to the Google Cloud SDK!

To use the Google Cloud SDK, you must have Python installed and on your PATH.
As an alternative, you may also set the CLOUDSDK_PYTHON environment variable
to the location of your Python executable.
Google Cloud SDK installer will now exit.
Press any key to continue . . . 
```
and the process then hangs.

**Comment by briandealwis** [comment]
On the console, I see:
```
Feb 27, 2018 12:14:23 PM com.google.cloud.tools.managedcloudsdk.install.Downloader download
INFO: Downloading https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz to C:\Users\IEUser\AppData\Local\google-cloud-tools-java\managed-cloud-sdk\downloads\google-cloud-sdk.tar.gz
```
and nothing else.  Would be useful to have a little bit more logging info.

**Comment by loosebazooka** [comment]
There is a windows specific archive with bundled python that I'll change this to.... on the pausing, I thought we ran everything with --quiet, but I'll look again

**Comment by loosebazooka** [comment]
I guess all the test machines have python on the path.

**Comment by chanseokoh** [comment]
I just noticed that on Windows, the following prompt appears even on successful installation and `SdkInstaller.install()` won't return.

```
Google Cloud SDK installer will now exit.
Press any key to continue . . . 
```

**Comment by briandealwis** [comment]
I mentioned that to @loosebazooka yesterday on hangouts:
> I think you need to run install.sh and install.bar with —disable-prompts: https://cloud.google.com/sdk/downloads#non-interactive_silent_deployment

**Comment by loosebazooka** [comment]
`--quiet` should disable prompts from the script we're using, I'm going to have to ask the cloud sdk team about that too.

**Comment by chanseokoh** [comment]
`--disable-prompts` is for the installer shell script on Linux: `install_google_cloud_sdk.bash`. Moreover, we don't even download or use that install script. We just call `install.sh` included in the downloaded archive.

**Comment by loosebazooka** [comment]
I think we can use `call install.bat....` to prevent windows from injecting this PAUSE ?

**Comment by chanseokoh** [comment]
One workaround for the inject `PAUSE` is to make `echo` do the keystroke:

```java
    script.add("cmd.exe");
    script.add("/c");
    script.add("@echo");
    script.add("|");
    script.add("install.bat");
```

This works in my testing. Not sure if it should be `@echo | call install.bat"` or if `cmd /c` is unnecessary.

**Comment by briandealwis** [comment]
The [docs on `—disable-prompts`](https://cloud.google.com/sdk/downloads#non-interactive_silent_deployment) say it should work for the Windows install.bat too:

<img width="701" alt="screen shot 2018-02-28 at 9 45 27 pm" src="https://user-images.githubusercontent.com/202851/36824511-c68405ba-1cd0-11e8-9d21-701c67eadd36.PNG">

The `install.sh`/`install.bat` are simply wrappers around invoking Python on `google-cloud-sdk/bin/bootstrapping.install.py`.  Oddly, running `install.sh —help` doesn't list `—disable-prompts`, but does include `—quiet`, and `install.bat —disable-prompts` doesn't seem to do the right thing on Windows:
```
C:\Users\IEUser\AppData\Local\Google\Cloud SDK\google-cloud-sdk>install.bat --disable-prompts
Welcome to the Google Cloud SDK!
usage: install.py [-h] [--usage-reporting USAGE_REPORTING] [--rc-path RC_PATH]
                  [--command-completion COMMAND_COMPLETION]
                  [--path-update PATH_UPDATE] [--disable-installation-options]
                  [--override-components [OVERRIDE_COMPONENTS [OVERRIDE_COMPONENTS ...]]]
                  [--additional-components ADDITIONAL_COMPONENTS [ADDITIONAL_COMPONENTS ...]]
                  [--quiet]
install.py: error: unrecognized arguments: —disable-prompts
```

But looking at the `install.bat`, it does invoke `PAUSE` but does check for some variables:
```
echo %CmdCmdLine% | find /i "%~0" >nul
SET INTERACTIVE=%ERRORLEVEL%
[…]
IF _%INTERACTIVE%_==_0_ (
  IF _%CLOUDSDK_CORE_DISABLE_PROMPTS%_==__ (
    echo Google Cloud SDK installer will now exit.
    PAUSE
  )
)
```
It looks like setting `CLOUDSDK_CORE_DISABLE_PROMPTS=1` before running `install.bat` should do the trick.

**Comment by briandealwis** [comment]
Another possibility would be to invoke `bin/bootstrapping/install.py` directly.
