### ISSUE TITLE
PathResolver should also look for google-cloud-sdk in managed SDK locations

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#560]
Probably should prefer them if present.

**Comment by loosebazooka** [comment]
Do we still need path resolution here? Build tools are going to default to downloading an SDK if not present or using a user defined value if specified?

**Comment by elharo** [comment]
Eclipse is still using this. Arguably it should just use a managed SDK, though it does help with some offline use cases. Let's discuss further.

**Comment by JoeWang1127** [comment]
close as not planned
