### ISSUE TITLE
Google LLC

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#564]
New Google standard is that this takes the form 

```
 * Copyright 2016 Google LLC. All Rights Reserved.
```

That is,

* Google LLC, not Google Inc.

https://g3doc.corp.google.com/company/teams/opensource/copyright.md?cl=head

**Comment by loosebazooka** [comment]
fixed by https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/756
