### ISSUE TITLE
Pass --application flag to devappserver1 and 2.

### ISSUE THREAD

**Issue by coollog** [GoogleCloudPlatform/appengine-plugins-core#567]
This will be used in https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/236 to run devappserver1 and devappserver2 with an application override.

**Comment by chanseokoh** [comment]
Personally, I don't like the name `--application`.

**Comment by coollog** [comment]
We will actually be using the `project` configuration as the app id to pass into the `--application` parameter for the devappservers (to keep it consistent with deployment).

**Comment by chanseokoh** [comment]
Oh, so the dev appservers already implements the `--application` flag.

We need to make sure the flag works especially in the context of multiple local run, as in GoogleCloudPlatform/app-maven-plugin#236.

**Comment by coollog** [comment]
devappserver2 currently implements `--application` but devappserver1 doesn't (I'm currently adding it to be the same as devappserver2).

**Comment by loosebazooka** [comment]
@coollog did this ever go through?

**Comment by coollog** [comment]
The `--application` flag was added to devappserver1 in 190109502. It has not yet been added to plugins though.
