### ISSUE TITLE
Set CLOUDSDK_PYTHON and clear PYTHONHOME and PYTHONPATH for managed Cloud SDK on Windows

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/appengine-plugins-core#568]
From https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2949#issuecomment-373540253

We need to ensure our auto-install and update does not fail under any circumstances.

I'll also file a bug upstream. I think it is a bug that `gcloud` is affected when `CLOUDSDK_PYTHON` is defined.

**Comment by chanseokoh** [comment]
Internal bug: 75262593

At the moment, we should clear the variables on our side.

**Comment by chanseokoh** [comment]
Well, actually, this affects not only install/update but just every `gcloud` invocation. Knowing that, it's probably WAI, especially on Linux where `gcloud` relies on the pre-installed Python.

However, for our managed SDK on Windows, because we always download the Python-bundled SDK, we should always set `CLOUDSDK_PYTHON` and clear `PYTHONHOME` for every `gcloud` usage, not just for maanged SDK install/update.

**Comment by MrFarhan** [comment]
![image](https://user-images.githubusercontent.com/26528236/86496041-0af7a500-bd95-11ea-95a8-5a3f7cf74e5c.png)
 i am facing above issue, below is the environment variable that i have saved,

C:\Users\muham\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.8

can anyone guide on how to install Google cloud sdk?

**Comment by TiansuYu** [comment]
Facing the same issues here, set up the wrong `CLOUDSDK_PYTHON` path in my `.zshrc`. Now basically the entire environment is paralysed with anything related with gcloud commands.

**Comment by loosebazooka** [comment]
@TiansuYu , @MrFarhan it appears your issues are not related to this repository. This is a project for java appengine users. See the description [here](https://github.com/GoogleCloudPlatform/appengine-plugins-core#google-app-engine-plugins-core-library). If you would like help with the cloud sdk, please see https://cloud.google.com/sdk/docs/getting-support

**Comment by chanseokoh** [comment]
I believe this no longer an issue for us (appengine-plugins-core and the build/IDE plugins). Also looks like b/75262593 is resolved.
