### ISSUE TITLE
OSGI issue with com.google.cloud.tools.appengine.cloudsdk.internal.process

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#589]
In CLI build:

[WARNING] Manifest com.google.cloud.tools:appengine-plugins-core:jar:0.5.3-SNAPSHOT : Export com.google.cloud.tools.appengine.cloudsdk,  has 1,  private references [com.google.cloud.tools.appengine.cloudsdk.internal.process],

**Comment by briandealwis** [comment]
I think the problem is that a `CloudSdk` has a bunch of methods that throw `com.google.cloud.tools.appengine.cloudsdk.internal.process.ProcessRunnerException`, which is an internal class and so not exported.

**Comment by briandealwis** [comment]
No more warnings after most recent round of refactoring.
