### ISSUE TITLE
Are CloudSdkGenRepoInfoFile and GenRepoInfoFile still used?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#593]
CloudSdkGenRepoInfoFile and GenRepoInfoFile don't seem used any more. Can IntelliJ confirm?

**Comment by etanshaul** [comment]
intellij is not using it either. I guess this was missed during @loosebazooka's cleanup?

**Comment by TadCordle** [comment]
It looks like it's still used in the appengine gradle/maven plugins.

**Comment by etanshaul** [comment]
ah. thanks @TadCordle. I'll close.
