### ISSUE TITLE
Windows users may hit MAX_PATH problems when installing Managed Cloud SDK

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/appengine-plugins-core#595]
[A user on StackOverflow](https://stackoverflow.com/q/49951737/600339) seems to be hitting an installation problem of the Managed Cloud SDK on Windows:
```
#============================================================#
#= Installing: gcloud app Java Extensions                   =#
#============================================================#
ERROR: gcloud crashed (IOError): [Errno 2] No such file or directory:  u'C:\\Users\\reddingBobulus\\AppData\\Local\\google-cloud-tools-java\\managed-cloud-sdk\\LATEST\\google-cloud-sdk.staging\\platform\\google_appengine\\google\\appengine\\tools\\java\\jetty93\\jetty-distribution\\lib\\apache-jsp\\org.eclipse.jetty.apache-jsp-9.3.18.v20170406-nolog.jar'
```
That path is 265 characters (including the terminating nul), which exceeds [Windows' maximum path length `MAX_PATH` (260)](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath).  This maximum path length can be removed in Windows 10, but is opt-in (!) by setting a registry key.

That same [MSDN article](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath) notes that there are many functions that have Unicode versions that permit an extended path length of 32767 characters.  Such extended paths can be specified with a `\\?\` prefix (e.g., `\\?\C:\Users\Foo\Bar`).  We should investigate whether this extended path prefix works.

**Comment by chanseokoh** [comment]
Gosh. Given the path, looks like this will happen quite frequently.

**Comment by elharo** [comment]
We should probably check for this in the managed cloud SDK installer and throw a relevant exception if it's a problem. What's the best way on Windows to check for the maximum path length? Is there anything more reasonable than creating a temporary file with a long path and seeing if it succeeds?

**Comment by briandealwis** [comment]
I can confirm that I can create a file with path length > 260 from `cmd.exe` using the `\\?\` prefix.

**Comment by chanseokoh** [comment]
I fear that gcloud may be the one to test and use `\\?\`.

I like the idea to test creating a temp file with a long name and if it fails, display explanation and instructions to enable long path names.

**Comment by briandealwis** [comment]
I suppose there's the same possibility that someone has put an `eclipse.exe.manifest` to enable long-path names for Eclipse

**Comment by chanseokoh** [comment]
I think the manifest approach (i.e., placing `python.exe.manifest` next to `python.exe`) won't work. It requires modifying the Windows registry to prefer the external manifest file: https://appuals.com/disable-display-scaling-on-high-dpi-devices-in-windows-10/

My GCE Windows did not set the `PreferExternalManifest` registry key by default. I verified the external manifest file is picked up only after defining the key.

**Comment by briandealwis** [comment]
Does that suggest that the python.exe has an embedded manifest?

**Comment by chanseokoh** [comment]
#605 will reduce the path length.

After the fix rolls out, we could eventually clean up SDKs in the deprecated locations (if any), after sufficient lead time. A working implementation for such cleanup is at https://github.com/GoogleCloudPlatform/appengine-plugins-core/compare/i595-reduce-path-len?expand=1.

**Comment by JoeWang1127** [comment]
close as not planned
