### ISSUE TITLE
Make formatting automatic or remove it

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#601]
I.e. `$ mvn com.coveo:fmt-maven-plugin:format`

Possibly we can bind this to the validate or compile phase. Otherwise it's wasting too much dev time. We should not run this manually. 

I.e. change the goal from check to format.

**Comment by loosebazooka** [comment]
The issue with this is that the test infrastructure will no longer catch unformatted files in a PR.

**Comment by elharo** [comment]
The issue is that we're constantly wasting time because files with trivial formatting errors get pushed. Either we should make the formatting automatic or we should remove the check. Wishy washy half-solutions are costing us serious developer time.

**Comment by loosebazooka** [comment]
With "2.4", the error message prints 
```
[ERROR] To fix formatting errors, run "mvn fmt:format"
```

Ideally the developer should be running `mvn verify` to verify tests/checks are passing before submitting anyway?

I'm not sure I get where the huge loss in productivity is coming from?

**Comment by elharo** [comment]
Don't make the user do work the computer can do. We don't live in an ideal world. nor in an dieal world would we want to make the developer run extra commands that can be automated. This is not theoretical.  We have lost a lot of time to this check. It's time for it to go.

**Comment by elharo** [comment]
FYI, I've now encountered a PR where the check fails but `mvn fmt:format` does *NOT* fix the problem,

```
[INFO] --- maven-checkstyle-plugin:2.17:check (default) @ appengine-plugins-core ---
[WARNING] src/main/java/com/google/cloud/tools/appengine/configuration/AppYamlProjectStageConfiguration.java:[89] (sizes) LineLength: Line is longer than 100 characters (found 114).
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:03 min
[INFO] Finished at: 2019-10-17T13:15:21-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default) on project appengine-plugins-core: You have 1 Checkstyle violation. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
elharo@elharo:~/appengine-plugins-core$ mvn fmt:format
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------< com.google.cloud.tools:appengine-plugins-core >------------
[INFO] Building App Engine Plugins Core Library 0.7.7-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- fmt-maven-plugin:2.4.0:format (default-cli) @ appengine-plugins-core ---
[debug] Using Google style
[INFO] Processed 100 files (0 reformatted).
[INFO] Processed 185 files (0 reformatted).
```

**Comment by JoeWang1127** [comment]
close as not planned
