### ISSUE TITLE
Cobertura --> Clover

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#623]
Or perhaps some other maintained coverage solutions.

https://confluence.atlassian.com/clover/clover-for-maven-2-and-3-user-s-guide-92504107.html

**Comment by briandealwis** [comment]
Clover hasn't had a commit since April 2017 when it was open-sourced. https://bitbucket.org/atlassian/clover

Jacoco works with codecov.io.
