### ISSUE TITLE
ManagedCloudSdkTest may be flaky on Mac

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#632]
Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 66.633 sec <<< FAILURE!
testManagedCloudSdk_latest(com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest)  Time elapsed: 39.038 sec  <<< ERROR!
com.google.cloud.tools.managedcloudsdk.command.CommandExitException: Process failed with exit code: 1

**Comment by JoeWang1127** [comment]
close as not planned
