### ISSUE TITLE
Provide API to get version of latest available Cloud SDK

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/appengine-plugins-core#636]
It would be nice if `ManagedCloudSdk` could provide the version of the latest available Cloud SDK so it could be shown to users (e.g., "Google Cloud SDK 202.0.0 is available.  You have 128.0.0.").  This doesn't seem to be available from `gcloud components list`.

**Comment by loosebazooka** [comment]
hrmm... @markpell @znewman01 @vilasj any ideas here?

**Comment by markpell** [comment]
Visually it does this, if you are not up to date you will see:

Your current Cloud SDK version is: 195.0.0
The latest available version is: 202.0.0

This is not programmatically consumable, however.

**Comment by briandealwis** [comment]
It would be nice if we could consume it programmatically!

**Comment by briandealwis** [comment]
Gleaned from #416:
```
$ gcloud info --format='value(basic.version)'
203.0.0
```

**Comment by JoeWang1127** [comment]
close as not planned
