### ISSUE TITLE
Null test exclusions

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#642]
Several test classes such as `com.google.cloud.tools.appengine.cloudsdk.CloudSdkAuthTest` are excluded from nullability checking because they check for NullPointerExceptions like so:

```
  @Test
  public void testNullSdk() {
    try {
      new CloudSdkAuth(null);
      Assert.fail("allowed null runner");
    } catch (NullPointerException expected) {
      // pass
    }
  }
```

We might want to move these checks into a separate test class so we only have to exclude that class, and all remaining tests can be checked.

**Comment by JoeWang1127** [comment]
close as not planned
