### ISSUE TITLE
StageFlexibleConfiguration docker directory should be nullable

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#660]
It's not required for flexible staging.

**Comment by patflynn** [comment]
@elharo Has this been broken for long?  I don't remember ever having an issue deploying without a docker directory specified.

**Comment by loosebazooka** [comment]
I don't think everyone used flex staging from plugins core.

**Comment by elharo** [comment]
No, this breakage is new in 0.6.1. I don't think we've shipped it anything.

**Comment by elharo** [comment]
If IntelliJ can deploy to the flexible environment java runtime (i.e. without a dockerfile) then it is affected by this bug.

**Comment by elharo** [comment]
Interesting. How does IntelliJ stage flexible applications?
