### ISSUE TITLE
Cloud SDK install: run install.sh outside the unzipped directory

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/appengine-plugins-core#666]
We are hitting https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/3157, which is not a usual situation. I think the situation happens when the Cloud SDK team rolls back a release, which makes installing the SDK effectively become a downgrading operation. Note

```
Welcome to the Google Cloud SDK!


Your current Cloud SDK version is: 205.0.0
Installing components from version: 204.0.0
```

The failure can be avoided if we run `install.sh` or `install.bat` outside the unzipped SDK root. Right now, [we are intentionally running `install.sh` inside the SDK root](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/v0.6.2/src/main/java/com/google/cloud/tools/managedcloudsdk/install/Installer.java#L68).

The same cure to #651 should work, I believe. (Note #651 was when installing the Java component and upgrading the SDK. We didn't fix it for initially running the install script.)

**Comment by Garyld21** [comment]
Yall hacker think yall getting away with this ..stealing my apps. Changing things ..
