### ISSUE TITLE
CloudSdk builder.build should not throw CloudSdkNotFoundException

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/appengine-plugins-core#678]
This is a little misleading because it's only thrown if the discovery mechanism fails, not if the path is invalid.

Discovery should probably be it's own function.

**Comment by chanseokoh** [comment]
That makes sense, but we need to be careful, as this change may trigger a chain reaction into many methods that require proper handling. For example, we use the following code to read the version of a Cloud SDK. If `build()` won't throw the exception, should `getDevAppServerPath()` throw it or not? There are other similar methods that we need to think about whether it makes sense to throw the `CloudSdkNotFoundException` or not, such as `getPath()` (probably not), `getJavaExecutablePath()` (probably yes), `getVersion()`, `getCloudPath()`, etc.

```java
      CloudSdk sdk = new CloudSdk.Builder().sdkPath(sdkHome).build();
      return sdk.getDevAppServerPath();
```

**Comment by briandealwis** [comment]
Perhaps we should do some very minimal validation of the SDK path in `build()`, like checking that there is an executable `gcloud` / `gcloud.cmd` in `bin/`?

**Comment by elharo** [comment]
Is there an issue that motivates this request?

I think that possibly we should also throw this exception on a bad manually supplied path. However I don't think we should not throw this from build on a discovered path.

Discovery is it's own private function now. I don't see a use case for a public API for this.

**Comment by loosebazooka** [comment]
I think the point here is that, no tools (eclipse/intellij/build) use this discovery at the moment. Catching that exception really messes with code flow when it is known it'll never be triggered. We'd probably have to change the builder to require a path instead of have it optional. If the programmer wants to discover it, then can pass in discovery to the builder.

```
CloudSdk sdk = CloudSdk.builder("sdk/path").build()
CloudSdk sdk = CloudSdk.builder(CloudSdkResolver.find()).build()
```
where `find()` throws the exception

**Comment by elharo** [comment]
I could have sworn Eclipse used that. I'll have to check. I don't like the idea of separating out a `CloudSdkResolver.find()` method just for this use case. If we genuinely don't need `discoverSdkPath`, then we should remove it completely and delete the code.

**Comment by elharo** [comment]
Eclipse is indeed using this; for instance on on line 76 of `CloudSdkprocessWrapper` and line 369 of `LocalAppEngineServerBehaviour`
