### ISSUE TITLE
Run nightly tests to catch URL moves and out-of-date artifacts

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/appengine-plugins-core#717]

**Comment by briandealwis** [comment]
I've configured the Travis job to rebuild master nightly.

**Comment by chanseokoh** [comment]
> I've configured the Travis job to rebuild master nightly.

Interesting. How/where did you do it? Is there a doc?

**Comment by chanseokoh** [comment]
Also, will we notified if the nightly builds fail?

**Comment by loosebazooka** [comment]
This should also help us catch the sdk breakages.

**Comment by briandealwis** [comment]
Go to the [Travis page](https://travis-ci.org/GoogleCloudPlatform/appengine-plugins-core) and open _More options > Settings_ and look at the bottom for _Cron Jobs_.

**Comment by JoeWang1127** [comment]
close as not planned
