### ISSUE TITLE
Upgrade to commons-compress 1.18.0

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#721]
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/network/alert/pom.xml/org.apache.commons:commons-compress/open

**Comment by loosebazooka** [comment]
Can we enable alerts directly on this project?

**Comment by briandealwis** [comment]
I think they just happen (shows up on my other projects).  Only visible to project owners though.
