### ISSUE TITLE
inject devappserver environment correctly (like KickStart.java)

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/appengine-plugins-core#745]
Replace https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1.java#L280

Perhaps it should look something like this (@ludoch):
```java
static String getGaeRuntimeJava(boolean isSandboxEnforced) {
    String gaeRuntime = "java7";
    if (System.getProperty("java.specification.version").equals("11")) {
      gaeRuntime = "java11";
    } else if (!isSandboxEnabled) {
      gaeRuntime = "java8";
    }
    return gaeRuntime;
}
```

**Comment by ludoch** [comment]
Do you have easily access to the appengine-web.xml object there?
If yes, you can get the runtime field from it.. It is always mandatory for the java11 case...
I

**Comment by loosebazooka** [comment]
yeah the PR reads it directly from appengine-web.xml (logic in: https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/744/files#diff-99f2a89bc597c0a1009b63d4b06c2414R278), but what is the expectation here that a jre11 should trigger runtime11? And should we match exactly what KickStart is doing?
