### ISSUE TITLE
Setters in builders

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#765]
Noticed while working on Eclipse. A lot of our builders look like this:

```
    Builder(Path sourceDirectory, Path stagingDirectory) {
      Preconditions.checkNotNull(sourceDirectory);
      Preconditions.checkNotNull(stagingDirectory);

      this.sourceDirectory = sourceDirectory;
      this.stagingDirectory = stagingDirectory;
    }
```

The problem with this pattern is that it is very easy to flip the source and staging directories since they have the same type. Methods such as `setSourceDirectory` and `setStagingDirectory` make it less easy to unintentionally mix up the arguments.

**Comment by suztomo** [comment]
(not directly related to the issue)
Because methods on `Preconditions` return the validated references, you can write validation and assignment in one line:

```
setSourceDirectory(Path sourceDirectory) {
      this.sourceDirectory = Preconditions.checkNotNull(sourceDirectory);
```

**Comment by loosebazooka** [comment]
I would take a look at everything in `com.google.cloud.tools.appengine.configuration` at all the builders and standardize the no-arg builder pattern for any in there that uses a new Builder(...args)

**Comment by elharo** [comment]
VersionsSelectionConfiguration looks OK because it only uses a single argument. StopConfiguration has both a Builder and a public constructor, which is weird. RunConfiguration only takes a single argument. DeployConfiguration only takes a single argument, so none of these have the swapped argument problem that but me.

**Comment by JoeWang1127** [comment]
close as not planned
