### ISSUE TITLE
toBuilder in RunConfiguration

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#766]
Eclipse needs to add jvmFlags after a run config is created:

```
    jvmFlags.add("-Xdebug"); //$NON-NLS-1$
    jvmFlags.add("-Xrunjdwp:transport=dt_socket,server=n,suspend=y,quiet=y,address=" + debugPort); //$NON-NLS-1$
    devServerRunConfiguration.setJvmFlags(jvmFlags);
```

Also we have cases where a RunConfiguration does not have deployables.

**Comment by briandealwis** [comment]
> Also we have cases where a RunConfiguration does not have deployables.

Really?  I can't think of why!

**Comment by elharo** [comment]
comparison of run configs; also tests. See `LocalAppEngineServerLaunchConfigurationDelegate.checkConflicts`
Possibly other places I haven't found yet.
