### ISSUE TITLE
Wrong type in getResolvers

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#773]
Serious bug in CloudSdk.Builder.getResolvers:

```
    /** Return the configured SDK resolvers. */
    @VisibleForTesting
    public List<CloudSdkResolver> getResolvers() {
      List<CloudSdkResolver> resolvers;
      if (this.resolvers != null) {
        resolvers = new ArrayList<>(this.resolvers);
      } else {
        // Explicitly specify classloader rather than use the Thread Context Class Loader
        ServiceLoader<CloudSdkResolver> services =
            ServiceLoader.load(CloudSdkResolver.class, getClass().getClassLoader());
        resolvers = Lists.newArrayList(services);
        // Explicitly add the PATH-based resolver
        resolvers.add(new PathResolver());
      }
      resolvers.sort(new ResolverComparator());
      return resolvers;
    }
```

The line `resolvers = Lists.newArrayList(services);` fails silently due to a type error. This affects Eclipse and probably others.

**Comment by briandealwis** [comment]
Is there a failure?  This code is unchanged from the original commit and CT4E relies on this code.

**Comment by elharo** [comment]
CT4E has a test failure. It's not a type error like I initially thought, but something is going on here such that a resolver isn't found. I'm still digging.

**Comment by elharo** [comment]
The issue's in Eclipse. The package changed so the the name of the file in META-INF/services needs to change to match.
