### ISSUE TITLE
IllegalStateException during Update Available check

### ISSUE THREAD

**Issue by karsai1993** [GoogleCloudPlatform/appengine-plugins-core#828]
Hi there,
I would like to deploy my Spring Boot app with the appengine-maven-plugin (v2.2.0) from my Windows 8.1 64-bit computer.

**Actual situation:**
Please, have a look at the following part of the stack trace:

> Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 2 column 1 path $
    at com.google.gson.Gson.fromJson (Gson.java:939)
    at com.google.gson.Gson.fromJson (Gson.java:892)
    at com.google.gson.Gson.fromJson (Gson.java:841)
    at com.google.cloud.tools.appengine.operations.cloudsdk.serialization.CloudSdkComponent.fromJsonList (CloudSdkComponent.java:67)
    at com.google.cloud.tools.managedcloudsdk.ManagedCloudSdk.isUpToDate (ManagedCloudSdk.java:153)

The problem is obvious: the [value of the result variable](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/src/main/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdk.java#L152) produced in 152nd line of ManagedCloudSdk class is not in json format.

I executed the following command in my machine with Command Prompt:

> gcloud components list --format=json --filter=state.name:Update Available
 
It resulted in an error because of the space character between the "Update" and the "Available": 

> ERROR: (gcloud.components.list) unrecognized arguments: Available

So, I think this error message is the one that is the value of the result variable. And as it does not have the json format, it throws an exception at:

`CloudSdkComponent.fromJsonList(result)`

**Expected situation:**
I tried the following command:

> gcloud components list --format=json --filter=state.name:"Update Available"

And it is working great, and produces an empty array as a result.
So, I am wondering what would be the result if updateAvailableCommand variable was created like this: 

`List<String> updateAvailableCommand =
				Arrays.asList(
						getGcloudPath().toString(),
						"components",
						"list",
						"--format=json",
						"--filter=state.name:\"Update Available\""
				);`

What do you think?

Thank you for your help and time in advance!

Best regards,
László

**Comment by loosebazooka** [comment]
Is this an issue with only windows 8.1? When passing a command to a process in Java, characters that need to be escaped are automatically escaped.

**Comment by chanseokoh** [comment]
> So, I think this error message is the one that is the value of the result variable.

I don't think so. I am pretty sure something different and interesting is going on.

**Comment by karsai1993** [comment]
@loosebazooka 
I am not sure if it is connected to Windows or its version. I have installed an Ubuntu OS with VirtualBox, and I could deploy without any problem.
The output of that command is [], so an empty array.

@chanseokoh 
I agree. Could you reproduce the error? I followed [this tutorial](https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..index#0) on my Windows 8.1 computer, and I got the exception.

**Comment by chanseokoh** [comment]
@karsai1993 could you clarify? That is, did you run the tutorial inside the Cloud Shell as instructed in the tutorial, or on your local Windows 8.1 command line?

**Comment by karsai1993** [comment]
@chanseokoh I did the steps on my local Win8.1 command line.

**Comment by chanseokoh** [comment]
Chances are that this plugin should have installed an auto-managed `gcloud` at `C:\Users\<your username>\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk`. I think the `gcloud components list` command you tried in `https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/828#issuecomment-580907767` probably executed a different `gcloud`, most likely the one on your `%PATH%` that you installed manually. Can you try explicitly executing the auto-managed `gcloud` like this?

```
C:\Users\<your username>\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk\bin\gcloud components list --format=json --filter=state.name:"Update Available"
```

And is it possible for you to update the source code of this repo to build a plugin with some debug code and test it out? It's almost impossible to guess what's going on with your `gcloud` unless we see the actual `gcloud` output inside the plugin. One thing for sure is that `gcloud components list` did not crash and exited clearly with an exit code 0.

**Comment by karsai1993** [comment]
@chanseokoh 
I executed the command that you mentioned:

> C:\Users\Laci\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk\bin\gcloud.cmd components list --format=json --filter=state.name:"Update Available"
> 
> Your current Cloud SDK version is: 277.0.0
> The latest available version is: 278.0.0
> 
> [
>   {
>     "current_version_string": "2020.01.17",
>     "id": "core",
>     "is_configuration": false,
>     "is_hidden": false,
>     "latest_version_string": "2020.01.24",
>     "name": "Cloud SDK Core Libraries",
>     "size": 13648273,
>     "state": {
>       "name": "Update Available"
>     }
>   }
> ]

And if I use the command set in %PATH%:

> c:\Users\Laci\src\appengine-plugins-core>gcloud components list --format=json --
> filter=state.name:"Update Available"
> 
> Your current Cloud SDK version is: 278.0.0
> The latest available version is: 278.0.0
> 
> []

So, yes, there is a difference. But I got proper json response for both cases.

I will keep this issue updated about my findings regarding the plugin.

**Comment by chanseokoh** [comment]
I've written a [tiny diagnosis program](https://github.com/chanseokoh/appengine-diagnosis) to print out the command result. Can you test it out?

```
$ git clone https://github.com/chanseokoh/appengine-diagnosis.git
$ mvn compile exec:java
```

On my Linux, I get output like
```
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ diagnosis ---
SDK home: .../chanseok/.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk
gcloud path: .../chanseok/.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/bin/gcloud
BEGIN result
[
  {
    "current_version_string": "2.0.51",
    "id": "bq",
    "is_configuration": false,
    "is_hidden": false,
    "latest_version_string": "2.0.53",
    "name": "BigQuery Command Line Tool",
    "size": 890339,
    "state": {
      "name": "Update Available"
    }
  },
  ...
]

END result
```

**Comment by karsai1993** [comment]
@chanseokoh Thank you for your effort!
It is actually working on my Win8.1 OS.
I got the following:

> [INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ diagnosis ---
> SDK home: C:\Users\Laci\AppData\Local\google\ct4j-cloud-sdk\LATEST\google-cloud-
> sdk
> gcloud path: C:\Users\Laci\AppData\Local\google\ct4j-cloud-sdk\LATEST\google-clo
> ud-sdk\bin\gcloud.cmd
> BEGIN result
> [
>   {
>     "current_version_string": "2.0.52",
>     "id": "bq",
>     "is_configuration": false,
>     "is_hidden": false,
>     "latest_version_string": "2.0.53",
>     "name": "BigQuery Command Line Tool",
>     "size": 890339,
>     "state": {
>       "name": "Update Available"
>     }
>   },
>   {
>     "current_version_string": "2020.01.17",
>     "id": "core",
>     "is_configuration": false,
>     "is_hidden": false,
>     "latest_version_string": "2020.01.31",
>     "name": "Cloud SDK Core Libraries",
>     "size": 13804542,
>     "state": {
>       "name": "Update Available"
>     }
>   }
> ]
> 
> END result

As I saw this `newManagedSdk ` method puts more attention on defining the `managedSdkDirectory` before calling the constructor. Then I guess, this is the difference that makes it able to run on my computer. So, at least, we know that the issue is not related to the command setup but the cloudPath  definition.

**Comment by chanseokoh** [comment]
This is very perplexing; I expected it to fail. Can you paste the whole stacktrace of the original error?

Just in case, do you configure [`<cloudSdkPath>`](https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/master/USER_GUIDE.md#cloud-sdk-configuration) in your `pom.xml`? Anything special, like using Java 11?

**Comment by karsai1993** [comment]
@chanseokoh 
I have not changed any configuration but it is working now on my Win8.1. It uses this path for the gcloud.cmd:

> INFO: submitting command: C:\Users\Laci\AppData\Local\google\ct4j-cloud-sdk\LATE
> ST\google-cloud-sdk\bin\gcloud.cmd app deploy --stop-previous-version --project...

When I ran the deploy command, it updated some part of the sdk. Maybe, that helped in my case.
I did not configure the cloudSdkPath in pom. No, java11 or other special things. And the app does not pull any other gson version.

**Comment by chanseokoh** [comment]
Great! Thanks for the update. I think it was a one-off issue with some particular Cloud SDK version and it's no longer manifesting after the Cloud SDK is fully up to date. For example, although I think it's different issue, recently we did have reports from Windows users about getting one-off non-critical error messages while upgrading SDK after the SDK team added support for Python 3 in recent versions. Hopefully with the latest SDK, you won't hit this issue anymore. I'll close the issue.

**Comment by karsai1993** [comment]
Thank you for your effort @chanseokoh :)
