### ISSUE TITLE
Make AppEngineException checked

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#84]
This indicates an unpredictable environmental condition, not a program bug. This is exactly what checked exceptions were designed for.

**Comment by loosebazooka** [comment]
I'm not actually sure what to do here. I think for the most part we use this as a configuration/execution exception, is there somewhere we are using it to detect programming errors?

**Comment by elharo** [comment]
Yes, this is backwards. If we were using it to detect programming errors, then it should be a runtime exception. Since we're using it to detect problems outside the context of the program itself, it should be a checked exception.

**Comment by elharo** [comment]
Just hit this again, this time with the subclass `CloudSdkVersionFileNotFoundException`.

**Comment by elharo** [comment]
2018-03-08 @loosebazooka agreed we can do this. I'll complete this the week of 03/20 is no one has grabbed it before then.
