### ISSUE TITLE
Add support for binaries in the java11 standard buildpath

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/appengine-plugins-core#840]
Currently, `artifact`s are presumed to be jars and processed according (inspected). This feature request is to allow non-jar `artifact`s as long as the user has defined a custom entrypoint in the `app.yaml`.

- [x] app entrypoint parsing (#839)
- [x] support binary buildpath in staging (#842)

**Comment by loosebazooka** [comment]
@ludoch

**Comment by loosebazooka** [comment]
Testing instructions

1. clone repo
2. ./mvnw clean install
3. modify pom config for app-maven-plugin in test app
```
<plugin>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>appengine-maven-plugin</artifactId>
    <version>2.2.0</version>
    <dependencies>
        <dependency>
            <groupId>com.google.cloud.tools</groupId>
            <artifactId>appengine-plugins-core</artifactId>
            <version>0.8.3-SNAPSHOT</version>
        </dependency>
    </dependencies>
</plugin>
```

**Comment by ludoch** [comment]
Tested with a Quarkus native application. Ship it. Please update the plugin
doc so the feature is easy to discover with Graal-VM native image binaries.
