### ISSUE TITLE
CloudSdk.getGCloudPath returns incorrect path for gcloud on PATH

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/appengine-plugins-core#848]
When CloudSdk.getGCloudPath is called with an empty SDK path, this could mean we are trying to use `gcloud` that is on PATH rather than in a absolute directory. In this case `getGCloudPath` returns `bin/gcloud` path which is incorrect, and should just return `gcloud` so it will be searched on system PATH.

**Comment by chanseokoh** [comment]
It's hard to believe that the class is broken in search `gcloud` on PATH at this point.

> When CloudSdk.getGCloudPath is called with an empty SDK path, this could mean we are trying to use gcloud that is on PATH rather than in a absolute directory.

I think this assumption is not correct. I just looked into `CloudSdk`, and looks like the contract is that the `CloudSdk` instance must be instantiated with a concrete SDK home. For example, if you are setting an SDK home with the builder by `CloudSdk.Builder.sdkPath(...)`, then it's your responsibility that you pass the right SDK home. If you don't call `CloudSdk.Builder.sdkPath()`, then [`CloudSdk.Builder.build()`](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/95f042bce31c51aa8a4780167cdfac9e4212f2e9/src/main/java/com/google/cloud/tools/appengine/operations/CloudSdk.java#L296-L304) will try its best to [discover a working SDK home](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/95f042bce31c51aa8a4780167cdfac9e4212f2e9/src/main/java/com/google/cloud/tools/appengine/operations/CloudSdk.java#L306-L332) in the system (including [searching `PATH`](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/95f042bce31c51aa8a4780167cdfac9e4212f2e9/src/main/java/com/google/cloud/tools/appengine/operations/CloudSdk.java#L346)). It's not that `getGCloudPath()` will dynamically search for an SDK home. The SDK home is baked into the class and static.

If `getGCloudPath()` is returning just `bin/gcloud`, maybe the chances are that you call `CloudSdk.Builder.sdkPath(Paths.get(""))`. Try `CloudSdk.Builder.sdkPath(null)` (or not calling it at all).

**Comment by ivanporty** [comment]
Thanks @chanseokoh! This makes sense. We are working on a single gcloud executor using `CloudSdk` and we will try to make sure this use case is properly covered. I will try to quickly test your suggestions in the meanwhile.

**Comment by chanseokoh** [comment]
Sounds like this is not an issue. Closing.
