### ISSUE TITLE
Add error log to CommandExitException.toString() by default

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/appengine-plugins-core#849]
Currently `CommandExitException` only reports an error code by default which is completely meaningless (Cloud SDK team confirmed they do not use exit codes to indicate any specific type of an error). Resulting error message is  `com.google.cloud.tools.managedcloudsdk.command.CommandExitException: Process failed with exit code: 1`. If we add error log by default, logging and diagnosing would be much easier.

**Comment by chanseokoh** [comment]
The exception message is always `Process failed with exit code: ...`, but I think `CommandExitException.getErrorLog()` will return stdout and stderr.

https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/95f042bce31c51aa8a4780167cdfac9e4212f2e9/src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandCaller.java#L70

**Comment by elharo** [comment]
In general `toString()` methods should not return more than one line of text. An entire error log is far too much. If you need the error log, that should be a new method, but it sounds like that method already exists?
