### ISSUE TITLE
Latest Cloud SDK not in cloud storage bucket

### ISSUE THREAD

**Issue by drei01** [GoogleCloudPlatform/appengine-plugins-core#863]
When running the appengine-gradle-plugin `downloadCloudSdk` task (which uses `SdkInstaller`), I get the following error that the sdk file is missing from the bucket

```
Excluding the following packages from import suggestions: [com.google.appengine.api.memcache, com.google.appengine.api.datastore, com.google.appengine.api.taskqueue, com.google.appengine.api.modules, com.google.apphosting.utils.remoteapi, com.google.apphosting.utils, com.google.appengine.api.appidentity, com.google.appengine.api.utils]
Execution failed for task 'downloadCloudSdk'. org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: https://storage.googleapis.com/cloud-sdk-release/google-cloud-sdk-326.0.0-linux-x86_64.tar.gz
```

The task works for all previous SDK versions, most recently 325.0.0.

Has the file moved or is this simply an oversight?

**Comment by loosebazooka** [comment]
Interesting. Maybe there's a release issue. @vilasj ?

**Comment by chanseokoh** [comment]
The link works now: https://storage.googleapis.com/cloud-sdk-release/google-cloud-sdk-326.0.0-linux-x86_64.tar.gz
