### ISSUE TITLE
Support for EAR based project staging and error messaging

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/appengine-plugins-core#88]
Currently this lib does not support staging and deployment for EAR based projects. The user is shown an error message indicating this, but the message does not provide any workaround suggestions.

If it doesn't make sense to add in this support then perhaps we should expand the error message guiding the user: i.e. deploy the modules individually instead.

Motivation: the IJ legacy App Engine plugin does support ear plugins.

**Comment by sparhomenko** [comment]
Are there any updates on whether EAR support is planned to eventually be added to the new Cloud SDK-based plugins?

**Comment by elharo** [comment]
EAR support is not planned. 

This library should probably not expand its error messages since it's not user facing, and messages are not localized. Detailed messages like that belong in the user facing components such as CT4I.
