### ISSUE TITLE
"--add-opens" flags are being added to JDK 8 invocations

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/appengine-plugins-core#916]
This was found by a Cloud Code IntelliJ user of App Engine standard Java 8. Details here:
https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/3136#issuecomment-1522283942

This PR introduced some conditional logic to add `--add-opens` flags required for JDK11:
https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/894/files

However, despite having a JDK8 configured, and invoking the appengine runner in this lib, `--add-opens` is still being added (leading to failure due to non-support in JDK8):

```
com.google.cloud.tools.appengine.operations.DevAppServerRunner - submitting command: 
/Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java --add-opens 
java.base/java.net=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.http=ALL-UNNAMED 
--add-opens java.base/sun.net.www.protocol.https=ALL-UNNAMED -Duse_jetty9_runtime=true -D--
enable_all_permissions=true -Dappengine.sdk.root=/Users/.../google-cloud-
sdk/platform/google_appengine/google/appengine/tools/java -cp /Users/.../google-cloud-
sdk/platform/google_appengine/google/appengine/tools/java/lib/appengine-tools-api.jar 
com.google.appengine.tools.development.DevAppServerMain --address=localhost --port=8080 --
allow_remote_shutdown --disable_update_check --no_java_agent /Users/...
```

**Comment by etanshaul** [comment]
Looks to be because the runtime of the IDE plugin is different than the runtime of of the user's configured project (for which the local emulator runs). For example, I set up an app engine project to use JDK8, but the runtime of the plugin is JDK17 which is what is fetched by `StandardSystemProperty`.

**Comment by etanshaul** [comment]
One possible approach here would be to have the callers pass in the JDK version rather than have the lib try to infer it (where it could differ from the runtime actually used by the project being emulated).

**Comment by suztomo** [comment]
@etanshaul Doesn't "the runtime of the plugin" (or Cloud Code) use JAVA_HOME too?

**Comment by etanshaul** [comment]
> Doesn't "the runtime of the plugin" (or Cloud Code) use JAVA_HOME too?

The project the user has open in their IDE may use a completely different runtime from what is used to run the IDE and plugins. In this case, Cloud Code passes in the java home path configured by the _user's project_  to this library so it knows which runtime to use (e.g. when emulating a user's app engine application). I'm not sure if that answered the question though?

When I say the users project JDK in IntelliJ I'm talking about this:
<img width="901" alt="Screenshot 2023-04-25 at 9 34 12 PM" src="https://user-images.githubusercontent.com/1735744/234443520-62240b2f-7246-4573-8b52-c9ca44f180d8.png">

**Comment by suztomo** [comment]
Thank you for explanation.

I read that "the runtime of the plugin" is the JVM on which IntelliJ is running. That makes sense.

**Comment by etanshaul** [comment]
might be related to https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/916 which was since fixed (maybe need to bump the lib version?)
