### ISSUE TITLE
Copy all files from src/main/docker for staging

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/appengine-plugins-core#92]
Not only the Dockerfile from src/main/docker should be copied, but all the files and subdir content if any, as these files can serve as context files for the docker image build step.

**Comment by meltsufin** [comment]
This has been partially fixed by #106 for App Engine Flexible staging. The same fix still needs to be applied to App Engine standard staging.

**Comment by meltsufin** [comment]
@loosebazooka This has not been fixed for Standard staging. We only copy the Dockerfile, and not the other files in `src/main/docker`.

**Comment by loosebazooka** [comment]
What exactly is the compat usecase?

runtime: java? - no docker context allowed?
runtime: custom? - some arbitrary docker context?

**Comment by patflynn** [comment]
@loosebazooka I'm not sure I understand the question. the user doesn't control the runtime for compat.

**Comment by meltsufin** [comment]
@loosebazooka You're right, docker context makes no sense for standar/compat staging.

Note that you can use a custom Dockerfile for a compat app, but then you need to use an app.yaml with `enable_app_engine_apis: true` rather than `appengine-web.xml`, and the whole staging will go through flex staging anyway.

**Comment by meltsufin** [comment]
@loosebazooka  You can actually use a `Dockerfile` with `appengine-web.xml` because `runtime: custom` is automatically written into the `app.yaml` during translation from `appengine-web.xml` to `app.yaml` when a `Dockerfile` is detected in the staging directory.

**Comment by loosebazooka** [comment]
obsolete
