### ISSUE TITLE
Handle additional configuration files

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/appengine-plugins-core#93]
How should we handle [index.yaml] [cron.yaml] [dispatch.yaml] [datastore-indexes.xml]?

**Comment by loosebazooka** [comment]
@patflynn have we decided that users deploy this on their own?

**Comment by patflynn** [comment]
yes. However users do need a way of converting their xml files to yamls.

**Comment by meltsufin** [comment]
The xml files get converted to yamls automatically during staging, as long as they're in the WEB-INF. It's also worth noting that this concern only applies to standard environment.

**Comment by loosebazooka** [comment]
obsolete
