### ISSUE TITLE
Enable license header checking

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/appengine-plugins-core#94]
See: GoogleCloudPlatform/app-maven-plugin/issues/15

**Comment by loosebazooka** [comment]
so, we haven't done this yet?

**Comment by meltsufin** [comment]
Not yet, but an example of how to do it can be found in the [pom.xml of the appengine-maven-plugin](https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/master/pom.xml#L228).

**Comment by loosebazooka** [comment]
obsolete
